### ISSUE TITLE
AST view incomplete for typedefs

### ISSUE THREAD

**Issue by pgoodman** [compiler-explorer/compiler-explorer#1346]
```c
typedef struct x y;
```

The AST for this should show a `RecordDecl`, followed by a `TypedefDecl`, but it only shows a `RecordDecl`.

https://gcc.godbolt.org/z/-1zjCC

**Comment by steveire** [comment]
The processAstOutput in base-compiler.js strips out some AST output lines. It seems to be looking for the first use of `<source>` to find the first AST node from the main file. Because the typedef also uses `struct`, it declares a sibling `CXXRecordDecl` struct above the typedef. Because the `<source>` then doesn't get repeated (see https://github.com/mattgodbolt/compiler-explorer/issues/1175) and the typedef part of the AST is assumed to be irrelevant.

http://ce.steveire.com/z/GRk_PY

Probably all top-level decls after the first one at `<source>` should pass this filter.

**Comment by pgoodman** [comment]
```c
typedef struct x y;
struct x *z;
```

This doesn't show a `VarDecl` for `z`.

**Comment by steveire** [comment]
Everything that follows the `typedef struct x y;` is truncated because of the bug I pointed out before.

https://gcc.godbolt.org/z/gd9P7c

**Comment by mattgodbolt** [comment]
@necto as a recent contributor in this area of the code, do you happen to have any insights as to what might be going on here?

**Comment by necto** [comment]
Thanks for the ping, @mattgodbolt !
Yes, indeed, the problem is this regex:
https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/llvm-ast.js#L106
It does not match the last few lines of the AST produced from the OP's example:
```
TranslationUnitDecl 0xfd0908 <<invalid sloc>> <invalid sloc>

...
|-CXXRecordDecl 0x10119d0 <tmp.cpp:1:9, col:16> col:16 struct x
`-TypedefDecl 0x1011ad8 <col:1, col:18> col:18 y 'struct x':'x'
  `-ElaboratedType 0x1011a80 'struct x' sugar
    `-RecordType 0x1011a60 'x'
      `-CXXRecord 0x10119d0 'x'
```
Because it `TypedefDecl 0x1011ad8 <col:1, col:18> col:18 y 'struct x':'x'` mentions `col` and not `line` unlike most cases.
I'll open a fix PR in a couple of days.

**Comment by mattgodbolt** [comment]
Great detective work! Thanks @necto; I appreciate the help very much :)
