### ISSUE TITLE
Support -E output in some way

### ISSUE THREAD

**Issue by jorgbrown** [compiler-explorer/compiler-explorer#1380]
In https://godbolt.org/z/u-Tv3j , I show the bizarre nature of the C/C++ preprocessor, by using a macro that expands to a comma, which seemingly magically makes another macro work.

This is the input:

= - = - = - = - = - = - = - =
#define MACRO_COMMA ,
#define DEFINE_VAR(type, var) type var

DEFINE_VAR(int, global_integer);

DEFINE_VAR(std::unordered_map<int MACRO_COMMA int>, int_map);

DEFINE_VAR(std, "Weird godbolt bug");
= - = - = - = - = - = - = - =

But the weird thing is... that last line?  If I comment it out, the expansion of the previous line disappears.  This is true whether I use gcc or clang.

**Comment by apmorton** [comment]
appears to be caused by the combination of label and directive filtering.
only if both are on does the line disappear.

https://godbolt.org/z/yyGte0

the `std:` part of `std::unordered_map<int , int> int_map;` is being interpreted as an assembly label
if `std:` isn't detected as "used", and the unused label filtering is enabled it will get removed from the output.

anything that looks like a usage of a label called `std:` will cause the line to stay around, as can be seen here https://godbolt.org/z/HK12rG

you should probably turn off any filters that are meant to parse assembly when you are instructing the compiler to output something other than assembly.

not sure that this is really a bug in the filters, as they are technically doing what they are supposed to - its just that they are running on output they aren't meant to.

maybe it could detect usage of `-E` and disable filters meant for assembly output?

**Comment by partouf** [comment]
The assembly parser isn't really meant to support -E, it's expecting asm and not C++, so there's really nothing wrong.

We can consider disabling the parser on -E, but we would need to detect that on a per-compiler basis.

**Comment by claremacrae** [comment]
I wonder whether this is not sufficiently well-defined to have the "good-first-issue" tag? It sounds like some decision-making is required, and some understanding of disabling options "on a per-compiler basis"?

**Comment by partouf** [comment]
> I wonder whether this is not sufficiently well-defined to have the "good-first-issue" tag? It sounds like some decision-making is required, and some understanding of disabling options "on a per-compiler basis"?

Definitely. The 'good first issue' label is kind of a mess truth be told.

**Comment by jeremy-rifkin** [comment]
It would be really helpful to get special support for the preprocessor. Adding `-E` to the compiler flags works as expected most of the time but some lines are automatically filtered out by default, leading to confusing behavior. For example, https://godbolt.org/z/j35z6YET5.

**Comment by jeremy-rifkin** [comment]
<https://godbolt.org/z/j35z6YET5> is another good case of directive filtering leading to misleading output

**Comment by partouf** [comment]
this is fixed to my content with #3320
