### ISSUE TITLE
GHC 8.6.x fails with lack of memory in prod

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1412]
```
ghc: failed to create OS thread: Cannot allocate memory
```

Probably due to the 1.25GB virtual RAM limit we now enforce for compilations. Older GHCs seem ok.

**Comment by shachaf** [comment]
The GHC RTS maps 1TB of address space at startup and commits it as needed -- see <https://gitlab.haskell.org/ghc/ghc/issues/9706>. It looks like it respects address space rlimits (`RLIMIT_AS`/`ulimit -v`), so setting that limit would probably work here.

**Comment by shachaf** [comment]
...But it looks like `RLIMIT_AS` is already the mechanism for the 1.25GB limit, so it's probably not that simple.

**Comment by AlexanderCecile** [comment]
Can second the fact the 8.4.4 appears to be working fine. Great tool btw.

**Comment by apmorton** [comment]
possibly related ghc changes between 8.4.4 and 8.6.1

https://gitlab.haskell.org/ghc/ghc/commit/26273774661bd0780b1ae8f0755ea135a0ceaf92

**Comment by theindigamer** [comment]
mniip on one of the discord channels suggested using `--disable-large-address-space` at configure time (so you'd have to build GHC yourself), not sure if that is a feasible option.

**Comment by apmorton** [comment]
I ran into that compiler flag - was hoping there would be a way to fix this without building ghc, as we currently use the binary distributions.

When we switch over to nsjail we won't be limiting virtual memory at all (or not nearly as much), and instead limit resident memory.

Maybe we just do nothing and this will get fixed for free once nsjail lands?

Also wonder if it might be worth filing a bug with ghc about this?
Their new algorithm doesn't behave well with very low virtual memory limits - possibly there should be some lower threshold after which ghc reverts to the powers of 2 algorithm.

**Comment by theindigamer** [comment]
@apmorton I'm afraid I don't have any bright ideas. I'm not sure what the timeline is for nsjail -- if it might take a while, then you might want to consider making ghc-8.4.4 as the default to avoid confusing failures for people who don't know about this issue.

**Comment by siedentop** [comment]
@mattgodbolt  would it be possible to change the default Haskell compiler to 8.4.4 until this is resolved? I opened a new Haskell example, and  as a newbie it would be great if the default configuration worked.

**Comment by mattgodbolt** [comment]
@siedentop good idea, will do

**Comment by cptwunderlich** [comment]
That's a total hack, but would it be possible to slightly increase the memory limit? I've tested it locally with GHC 8.8.3 and it fails for a ´ulimit -v´ of 1.2 GB but works with 1.3 GB.

Also, is there a corresponding GHC ticket or should someone open one?

**Comment by cptwunderlich** [comment]
I've opened a ticket in GHC's Gitlab for this problem: https://gitlab.haskell.org/ghc/ghc/-/issues/18623

**Comment by cptwunderlich** [comment]
So after looking at the bug and talking with some people on IRC, it doesn't seem like there is a good fix on the GHC side.
What is going on:
GHC _reserves_ a large amount of virtual memory for it's runtime system (but this is not _committed_ memory). While they do try to respect the `ulimit` and I did try to leave some extra space for pthread stack space, that doesn't seem to reliably work. Sometimes one value crashes it, but a lower value won't. Figuring out how to make this work seems more difficult than anticipated.

Apparently other VMs/runtime systems do something similar. Running `javac -version` with a ulimit of 1GB give me an error as well:

> Error occurred during initialization of VM
> Could not reserve enough space for 524288KB object heap

This probably hasn't been an issue so far, bc. GCC, Clang, rustc, CPython all don't use a GC or runtime. But limiting **virtual** memory doesn't seem like a good solution anyway, when you want to limit resident set size (RSS). Unfortunately, RLIMIT_RSS doesn't work any more on kernels > 2.4.30.

I'm not very familiar with Compiler Explorers architecture, but I think you use firejail as sandboxing mechanism here and the `rlimit-as` option which uses `setrlimit`. Now I haven't seen any other way in firejail to limit RSS, but there is a `cgroup` option and cgroups are now the preferred mechanism for resource limits. You could create a cgroup with the given memory limit and add new tasks to it. I've tested that with GHC and it works.

Now I don't know if that solution is workable for you, since it would require a setup step where this cgroup would have to be created and that requires root privileges.

An alternative would be to add support for RLIMIT_DATA to firejail. This limits the process' data segment size. So process size would be something like data + code, but I'm not sure what else you would have to add to the calculation (stack sizes?).

**Comment by partouf** [comment]
@apmorton doesn't nsjail do things using cgroup? and if so, maybe we could specify per-compiler jailing so we can slowly transition out of firejail for various reasons for many of the compilers?

**Comment by partouf** [comment]
Todo for this:
* [ ] Test GHC in combination with nsjail and see if problem persists
* [ ] If fixed by using nsjail:
  - [ ] Make jail configurable per compiler
  - [ ] Put GHC 8.6.x under nsjail

**Comment by cptwunderlich** [comment]
It seems like it's working now on Compiler Explorer? Did you increase the vlimit?

Anyway, I implemented a workaround (PR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4106), it's being backported to 8.10.x, but I don't know whether they are still willing to make releases for 8.6.x.
I could ask, if you'd like. Of course that wouldn't fix the older 8.6.x releases in use.

I was also wondering whether I should create a PR here and at the infra repo for newer GHC versions, once releases with the fix are shipped (8.10.2 is current, 9 on its way).

**Comment by partouf** [comment]
We have not changed anything about the jail yet, no. We did change some AWS instance types, but that shouldn't have affected it, I think.

**Comment by RubenRBS** [comment]
This still works for me almost a year later. Should we call this "fixed"?

Also, we really should add new/updated GHC versions to the site. Tracking that in #2786

**Comment by cptwunderlich** [comment]
Yes, I would agree, it works.
