### ISSUE TITLE
Consider a benchmarking facility

### ISSUE THREAD

**Issue by cjdb** [compiler-explorer/compiler-explorer#1462]
Lots of people care about compile-time performance, and some people (like me) sometimes care about quick-and-dirty benchmarks (i.e. `time ./my-program` or `/usr/bin/time -v ./my-program`).

It'd be great if there could be an option in the interface to get stats for both how long it takes to compile a program and how long it takes to run a program.

**Comment by apmorton** [comment]
Recording the compiler and execution time server side would not be difficult, but I would question how useful it would end up being in practice.

Behind the scenes CE uses multiple different instance types on AWS, with no guarantees on what kind of cpu you are going to get.

Additionally, the compilers themselves are executed from network storage (NFS) which may have varying latency depending on the cycle of the moon.

There is already an "end to end" duration shown at the bottom of the compiler window, although this is timed in your browser so it will include network latency and variances.

If you click the refresh button next to this duration several times you can see just how much the same input can vary between multiple compilations.

We could certainly do better than client side duration, but I don't think it will be very reliable beyond orders of magnitude, which is about what the current client side duration can reliability tell you assuming your network connection is stable.

If we did clock duration server side it would have to be done inside firejail/nsjail for it to be of any use, since they themselves introduce around 80-100ms duration with a fairly significant variance.

**Comment by kunaltyagi** [comment]
@cjdb Why not quick-bench? Slightly convoluted, but simple enough

**Comment by mattgodbolt** [comment]
@kunaltyagi thanks for the link (and we're working on integration to make it easier to go back and forth between the two sites), but that covers only code run performance. To handle compile-time issues, `time -v` is a though but as @apmorton says, it's hugely dependent on which machine handles the request.

**Comment by kunaltyagi** [comment]
I thought the discussion was mostly aimed at runtime. Compilation timing is a coveted feature in compilers, not all of which provide detailed specs. Clang 9 (I believe, but I might be wrong) has some new flags for creating flame graphs for compilation times.

It might be interesting to use that maybe, instead of time, which is a pretty coarse indicator.

Using a few standard functions as standard candles removes the issue of machine dependence. The same function can function as a standard candle in runtime as well as compile time benchmarking.

```
void test_func()
{
  int a = 0;
  DO_NOT_OPTIMIZE(a);
  // do what you want with a, pass it to a function of your choice
}
```

Divide all times with the timings reported for `test_func` and machine-independent reports (mostly. Architecture variance affects floating-point, cache misses, etc. but for those, why not test on the target platform anyways?)

**Comment by pizzard** [comment]
For compile time tracing, there is already issue #1186.

**Comment by partouf** [comment]
This is kind of implemented through the timing graphs we launched recently.

**Comment by kunaltyagi** [comment]
How do I access that? I saw nothing specific to this in "More", "Add tool" or "Add new" (on godbolt.org for C++)

**Comment by RubenRBS** [comment]
Sorry about our _mediocre_ UX
I think there's something to be said about the fact that you looked for it in those places! Maybe we should think about what goes where more thoughtfully

The new timing graphs that @partouf made can be found under the compiler output, in its footer toolbar:
![imagen](https://user-images.githubusercontent.com/5364255/112933411-16a7aa80-9120-11eb-865c-bb0db9a602c4.png)

**Comment by kunaltyagi** [comment]
I think the UI just needs a manual 😄 

Some screenshot based (or if you're into it, JS based like https://introjs.com/ ) list of features in a README somewhere would be sufficient. I can gather some features into a README, if it's ok (and a web intro isn't on the roadmap)

**Comment by partouf** [comment]
> I think the UI just needs a manual 😄
> 
> Some screenshot based (or if you're into it, JS based like https://introjs.com/ ) list of features in a README somewhere would be sufficient. I can gather some features into a README, if it's ok (and a web intro isn't on the roadmap)

We do occasionally tweet about bigger changes: https://twitter.com/CompileExplore/status/1370131359050698759

But I could get into a readme if it's written in a way that it leaves some room to not always have to change it when we change something slightly.

**Comment by claremacrae** [comment]
Maybe there should be a separate issue for a user guide - but just add a huge 👍  to this...

As an occasional user of CE, I know that I've seen people demo features, but I struggled recently to demo very basic functionality to someone - and it would have been wonderful to start from...

Tweeting new features is great to draw people in, but it's not the first place I would look, to try to work out how to do something....
