### ISSUE TITLE
[REQUEST] Linker Error With MSVC in Execution Only Mode

### ISSUE THREAD

**Issue by christophercrouzet** [compiler-explorer/compiler-explorer#1502]
**Describe the bug**
Running any C/C++ code ain't possible when using a msvc compiler in 'Execution only' mode. The error printed out is `LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'`.

**To Reproduce**
Paste the code below and add a new 'Execution only' panel, with the 'x64 msvc v19,14' compiler set.

```c
int main(void)
{
    return 0;
}
```

**Link**
https://godbolt.org/z/4HnIJI

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 68

**Comment by apmorton** [comment]
Execution is not supported on any MSVC compiler currently.
The wine compilers run on our infrastructure, but are not able to produce a binary.
The non-wine compilers run on microsoft's infrastructure and we have no control over them.

I believe it is a bug that these compilers even show up in the dropdown on the execution only pane.

https://godbolt.org/z/JUUB5J

Notice the `./a.out` button is disabled in the compiler view, but the execution only view doesn't indicate in any way that execution is not supported with this compiler.

@RabsRincon I suppose the execution view doesn't filter the compiler drop down at all?

Only question is how to handle this from a UI perspective?

- filter unsupported compilers from the list entirely
  - visually the cleanest, but we may get bug reports like "xxx is missing from the execution pane"
- display them in the dropdown, but grayed out and unselectable - possibly with tooltip on hover saying something to the effect of "execution is not supported on this compiler"
  - doesn't cut down on clutter in the list, but is probably the least ambiguous
- do nothing client side, add checks server side and fail fast with an error message stating execution is not supported
  - should probably do this in any case for external API consumers

**Comment by christophercrouzet** [comment]
Thanks @apmorton! When you say that execution is not supported on msvc compilers _currently_, does this mean that there are plans to make it work sometimes in the future, or is this not something that won't be possible due to the technical constraints that you mentioned?

**Comment by partouf** [comment]
There are no plans, nor will there be any plans any time soon (think years). Luckily we have other C++ compilers that can execute your code probably exactly the same way ;)

**Comment by christophercrouzet** [comment]
> Luckily we have other C++ compilers that can execute your code probably exactly the same way ;)

Yes and no—I've been wanting to use Godbolt when not having access to a compiler locally, and not being able to execute code with msvc makes it impossible to test snippets with compiler-specific code. So far I've been using rextester as an alternative but I would have much preferred sticking to Godbolt if I had the choice.

But that's ok, no worries. Thanks for your work! 👍

**Comment by RabsRincon** [comment]
Note that this boils down to us not administrating the compilers which run on Windows, which are kindly supported internally by Microsoft. We just pass along the compilation request to their own instance of the site.

This means they dont support features which other compilers do, due to the fact that they run externally to us :)

One way or another, thank you for your report and for making sure we were not leaving msvc behind unintentionally!

**Comment by ubsan** [comment]
Please open a [Developer Community][DevComm] issue! We can't do anything about it if people don't ask for it on our website, and it helps us gauge interest! (no promises on anything coming to fruition, but it helps a lot if there is enough interest)

[DevComm]: https://developercommunity.visualstudio.com/spaces/8/index.html

**Comment by christophercrouzet** [comment]
Thanks @ubsan! For reference, I followed your advice and opened an issue there, see https://developercommunity.visualstudio.com/idea/663829/allow-code-execution-on-godboltorg-for-msvc-compil.html.

**Comment by LeslieGerman** [comment]
Thanks @christophercrouzet , I joined your request on developercommunity!

**Comment by TSlivede** [comment]
Execution with msvc seems to work, if one explicitly specifies the library locations:

https://godbolt.org/z/z941sc

I found the paths by looking at the output when compiling with [`/showIncludes`](https://docs.microsoft.com/en-us/cpp/build/reference/showincludes-list-include-files) and then comparing the paths to my local `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\` and `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\` folders (and some guessing).

**Comment by partouf** [comment]
> Execution with msvc seems to work, if one explicitly specifies the library locations:

There are good reasons why linking and execution is not enabled by default. Please don't use this as a workaround.

**Comment by TSlivede** [comment]
>There are good reasons why linking and execution is not enabled by default.

If linking and execution were actually disabled (i.e. it just doesn't try to execute something and prints a nice message like "executing is not supported") then I would have fully understood that. (Security, resource consumption, etc.).

However, the current behavior (trying to compile and then aborting on error) seemed to me, as if just nobody yet had the time or dedication to fix this "bug" (It is labeled as "bug" in this issue).

If it actually is supposed to be "disabled" and I blurted out a security issue (that I should have only published much later after responsible disclosure), then I'm really sorry. The issue in this conversation just didn't look like it was a security issue.

To make it clear to users, that this is in fact not a bug but an intentionally disabled feature, you might want to consider to
 - rename this github issue from "[BUG]" to "[feature request]"
 - remove the "Executor from this" option from the "Add a new pane" menu in the compiler pane if msvc is selected
 - dimm or grey out the whole executor pane (if msvc is selected) and display a message that it's not supported. (You might want to do this even if you make it impossible to add such a pane, because there can still be old "share" links, that have such an executor pane with msvc enabled)

**Comment by partouf** [comment]
> > There are good reasons why linking and execution is not enabled by default.
> 
> If linking and execution were actually disabled (i.e. it just doesn't try to execute something and prints a nice message like "executing is not supported") then I would have fully understood that. (Security, resource consumption, etc.).
> 

If you read this thread you would know this was already discussed.

> However, the current behavior (trying to compile and then aborting on error) seemed to me, as if just nobody yet had the time or dedication to fix this "bug" (It is labeled as "bug" in this issue).
> 
> If it actually is supposed to be "disabled" and I blurted out a security issue (that I should have only published much later after responsible disclosure), then I'm really sorry. The issue in this conversation just didn't look like it was a security issue.

It was only realized recently after having neglected to look at the various execution filtering mechanisms, that this could be important because of exploits on systems other than our own. We have secured these things from day 1 so an execute here or there would not have mattered to the compilers that we manage, but the MSVC compilers are remote and not managed by us.

I think it was a mistake for us to not realize the security issues sooner. But even if we would have, we would not have fixed the underlying issues because the MSVC compilers are not managed by us.

> To make it clear to users, that this is in fact not a bug but an intentionally disabled feature, you might want to consider to
> 
> * rename this github issue from "[BUG]" to "[feature request]"

Will do.

> * remove the "Executor from this" option from the "Add a new pane" menu in the compiler pane if msvc is selected

This is fixed.

> * dimm or grey out the whole executor pane (if msvc is selected) and display a message that it's not supported. (You might want to do this even if you make it impossible to add such a pane, because there can still be old "share" links, that have such an executor pane with msvc enabled)

A front-end mechanism is in place, but this is not a real solution.

> Edit: Is there a way (within github) to provide additional information, that will be only visible to repository maintainers/authors? Because if this is a security issue, I'd have an easy suggestion how to prevent the vulnerability. However my suggestion would also make it fairly easy to guess what this vulnerability was, so I don't want to just post it publicly (just in case the compiler explorer team actually does consider this as a vulnerability.)

I would suggest mailing matt at godbolt dot org

> Edit2: I Have a suggestion, that does not give away the vulnerability: Add a access control entry to the ntfs permission of the folder where files will be written, that denies execute permission to files.

The situation is a bit more complicated than just that, but sure, that's one of the things to be done. Rest assured there will be a lot of people looking at this issue next week.

Thank you for your comments in any case.

**Comment by partouf** [comment]
Closing this in favor of https://github.com/compiler-explorer/compiler-explorer/issues/1879
