### ISSUE TITLE
[BUG] Cannot generate a.out when using parallelism TS

### ISSUE THREAD

**Issue by fstark** [compiler-explorer/compiler-explorer#1625]
**Describe the bug**
We should be able to generate an a.out when using the parallelism TS.
Today, we get a link error, due to the lack of link support for the TBB library. I don't think we should have to manually add the tbb library if the compilers rely on it for the // TS, but if we do have to, it should not fail at link time.

**To Reproduce**
Make some standard code which uses parallel execution, add tbb as a library (required by clang and gcc), and generate an a.out

**Expected behavior**
No link error on tbb.

**Link**
https://godbolt.org/z/aaRmMX

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Firefox

**Additional context**
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0024r2.html

**Comment by mattgodbolt** [comment]
I don't know anything specifically about the parallelism TS - I appreciate any help!

**Comment by JacobALundgren** [comment]
There also seems to be a somewhat broader issue for the setup of `clang`, simply including the `execution` header causes compilation failure due to a missing `tbb` header:
https://godbolt.org/z/-SadDC

Meanwhile, with `gcc` it seems to work:
https://godbolt.org/z/rQiWZ-

For reference,
**Desktop (please complete the following information):**
- OS: Windows 10, 10.0.17134 Build 17134
- Chrome 79.0.3945.117

**Comment by RabsRincon** [comment]
As a workaround for this specific issue if you find it. Intel TBB is availale to be included, so you only need to add it to the include path, the easiest way being to select it in the Library dropdown
![imagen](https://user-images.githubusercontent.com/5364255/71972714-7f4df300-320d-11ea-9e47-e8e08221914e.png)
Once selected, the example provided does compile :)

**Comment by partouf** [comment]
Linking against TBB is now possible on the live site. Thread -> https://github.com/compiler-explorer/compiler-explorer/issues/2079
