### ISSUE TITLE
[LIB REQUEST] Add copperspice library to compiler explorer

### ISSUE THREAD

**Issue by janwilmans** [compiler-explorer/compiler-explorer#1670]
It would be super handy to have https://github.com/copperspice/copperspice (master) available on compiler explorer

**Comment by mattgodbolt** [comment]
Hi @janwilmans - yay ! We encourage library authors to submit PRs for their own libraries and have tried to make it as simple as possible! https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingALibrary.md gives fairly detailed instructions on how to do it! Two PRs are needed: one in the https://github.com/mattgodbolt/compiler-explorer-image repo and one here. Cheers!

**Comment by partouf** [comment]
This has been blocked for a while because of issues I encountered during my attempt to add this to CE.
I however do not remember what those issues were at the time.
So I'm guessing a retry is in order and document what went wrong.

**Comment by partouf** [comment]
Perhaps it doesn't have to be so complicated if there was to be a cmake target/defines to only generated the include folder. Would that be possible @janwilmans ?

**Comment by partouf** [comment]
> I'm not sure what you mean with 'only generate the include folder', copperspice is not a header only library, so a bunch of .so files are needed at runtime. If you 'make install' then you will get a

The fact that Cs is not header-only doesn't really matter. For the default assembly view that CE shows, only the compiler is invoked and no linking is involved. The way C/C++ work is that at that point you only need whatever file you `#include`.

A lot of github repo's usually just supply their headers and sources in the same structure as they intend it to be used by users. So that just cloning/pulling the repo will result in us having for example the `src` directory, and we can make the compiler get the headers from there. But for Copperspice, the directory structure in-repo is not the same as after-build.

And because our nightly-git-pulling instance has the processing power of a peanut, we do not build anything there. But we can run light scripts that can maybe do something to make it right. So that's why I asked if there was maybe a CMake setting to produce the correct include directories without having to build it.

We could also just write a bash script that copies all the headers to the correct folders.

> However, I do see what you mean, because after that, how do I actually build again this? I usually use the cmake scripts in lib/cmake, maybe we could also do this here?

That's not really a problem, because .so files are produced, they don't need to be in exact order when linking, so we can just provide `-lCsCore1.7 -lCsNetwork1.7` etc to the linker.

> About 'missing dependencies', as long as the library builds the .so files, the 'missing dependencies are usually not a problem, specific hardware support might be unavailable, but that's not usually a problem.

Ok, it was more a question of - if for example libCsGui is missing, how many people will complain that their code won't execute on CE.

**Comment by janwilmans** [comment]
Ah, I understand a bit more now. Would it help if I offer the pre-build result in a separate repo ?

**Comment by partouf** [comment]
> Ah, I understand a bit more now. Would it help if I offer the pre-build result in a separate repo ?

That would also be an option, but it would have to be up-to-date whenever the head commit has changed. I'm not sure that's easy to setup with a separate repo.

**Comment by janwilmans** [comment]
What if it would only point to the separate repo? then it just updates whenever we re-run the offline build (which could be manually, or automatically nightly)

**Comment by partouf** [comment]
Sure that might work

**Comment by janwilmans** [comment]
this being said, to actually run the program, I guess you _do_ need to .so's to be present, for what environment should they be build ?

**Comment by janwilmans** [comment]
We should talk about what's missing, why is 'ninja install' not doing what
you want?

**Comment by partouf** [comment]
Well, right now it doesn't build for me, not sure what's going on.

But I saw there are pre-builts https://github.com/copperspice/copperspice/releases/tag/cs-1.8.0
I think we might be able to use those

**Comment by janwilmans** [comment]
That would also be fine, however, if you let me know what platform you're using and what the error is, I might be able to help with that too.

It would help to know how you're invoking cmake.

**Comment by partouf** [comment]
This is now live

**Comment by janwilmans** [comment]
[compiler-explorer](https://godbolt.org/z/x4vxceEdq) adding the copperspice library and using clang seems not to find the copperspice headers

**Comment by partouf** [comment]
> [compiler-explorer](https://godbolt.org/z/x4vxceEdq) adding the copperspice library and using clang seems not to find the copperspice headers

You did not select Copperspice for the clang compiler here, if you do, it does work https://godbolt.org/z/M5cGdTrz3

**Comment by janwilmans** [comment]
you are right, my mistake, however, only CsCore is working, other libraries such as CsGui are not found ?
https://godbolt.org/z/drh9qezY6

**Comment by partouf** [comment]
We don’t have OpenGL installed so I left that out

**Comment by janwilmans** [comment]
Can we still add CsGui ? It is perharps the most important part of copperspice

**Comment by janwilmans** [comment]
Thank you for adding Cscore, it is already working very nice. Btw, can you shared the configuration files? I'd also like to setup an internal CE server.

**Comment by partouf** [comment]
> Thank you for adding Cscore, it is already working very nice. Btw, can you shared the configuration files? I'd also like to setup an internal CE server.

In the end I used the github release that was published, https://github.com/copperspice/copperspice/releases/download/cs-1.8.0/copperspice-1.8.0-ubuntu20.04-x64.tar.bz2

And then added it to our libs list https://github.com/compiler-explorer/compiler-explorer/blob/8afe2197e1fca745adadf3cb2fa834b1fbd00d3f/etc/config/c%2B%2B.amazon.properties#L3047

(full commit https://github.com/compiler-explorer/compiler-explorer/commit/e72fdf91dc37665cd0d05933c10af7c8149be3e6)
