### ISSUE TITLE
[REQUEST] Way of passing `GOARCH` to the go compiler

### ISSUE THREAD

**Issue by alex** [compiler-explorer/compiler-explorer#1698]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to see what Go's compiler emits for non-x86 archs (specifically `aarch64`). In Go cross-compiling is specified with the `GOARCH` environment variable. You can pass command line flags to the compiler in compiler-explorer, but there's no way (that I can tell) to set env vars.

**Describe the solution you'd like**
Some way to specify that I want to cross-compile for another arch. I don't have an opinion on what the UI for this should be.

**Comment by partouf** [comment]
A while ago a bunch of Go architectures were added to the compiler selection. (instead of having a UI input thing on it)
The supporting code adds new properties/configuration (https://github.com/compiler-explorer/compiler-explorer/blob/master/etc/config/go.amazon.properties#L99) and then transmits that as GOARCH (https://github.com/compiler-explorer/compiler-explorer/blob/master/lib/compilers/golang.js#L224)

So I think we can close this issue
