### ISSUE TITLE
Is there a contribution document that helps people to get involved into your project?

### ISSUE THREAD

**Issue by StephenChips** [compiler-explorer/compiler-explorer#1752]
For example, docs that shows the brief design of the software.

**Comment by RabsRincon** [comment]
Hi.
There are a few places that might be interesting to look at: The [Readme section Developing](https://github.com/mattgodbolt/compiler-explorer/blob/master/README.md#developing) and the [Contributing doc](https://github.com/mattgodbolt/compiler-explorer/blob/master/CONTRIBUTING.md)

Nevertheless it is true that they are a bit lacking at the moment, so please feel free to ask any questions that you feel are left unanswered in those files so we can improve them in the proces :)

**Comment by mattgodbolt** [comment]
Hey @StephenChips - is there anything else you think would be helpful? Perhaps more design, or other high level documentation?

**Comment by RubenRBS** [comment]
Ever since this issue was created, we have made some improvements on both our documentation and our `good-first-issue` approach (Thanks @claremacrae! 😄)

There's lots of room to improve though, starting with the creation of the mentioned
> brief design of the software.

document, which I think would be of great value if done correctly. Will poke around to get it done soon-ish :)

I'll close this issue in favour of the linked one
