### ISSUE TITLE
Request to change stylesheet to fix "maximised"

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#1812]
Via email:

"
Hi, when I maximize the browser window, I can move my cursor all the
way to the right of the screen and click the scroll bar to scroll. ...this does not work as expected because the mouseclick hits the border of parent div lm_content.

I propose appending to the stylesheet the following two lines:

```
.lm_content{border-right:none;} /* fix scroll */
.top-bar.btn-toolbar.bg-light{border-right: 1px solid #ccc;} /* keep looks */
```

"

**Comment by partouf** [comment]
I'm not sure what this is about, I've tried a few browsers and hit F11 to go full screen, but it doesn't look/work any different than normal.

**Comment by apmorton** [comment]
The expectation is that you should be able to throw your cursor all the way to the right of the screen when your browser is maximized and click on the scroll bars. Currently if you move your cursor all the way to the right you will miss the scroll bars of our goldenlayout windows because lm_content has a 1px border on all sides, and the scroll bars are contained within lm_content.

Removing the border on the right hand side of lm_content does indeed fix this behavior. I did not test the visual fix proposed, and at first glance I am not super confident it would cover all potential visual changes.

Although to be fair we are talking about a 1px difference here - it's not something that really stands out visually to begin with.

**Comment by partouf** [comment]
I know we changed *something* about this last year, but not sure when or how and if it fixed this.

**Comment by RubenRBS** [comment]
I can't repo anymore either. Closing for now, but please feel free to repoen if I'm just being dumb and missed _how_ to repro it :)
