### ISSUE TITLE
[BUG] Short url can end in a - (dash). Not all url parses can handle this, resulting in broken links.

### ISSUE THREAD

**Issue by daantimmer** [compiler-explorer/compiler-explorer#1902]
**Describe the bug**
I guess see title

**To Reproduce**
Click share, short url, hope for a dash at the end

**Expected behavior**
A common parseable url without a dash at the end

**Link**
https://godbolt.org/z/PiycZ-

**Screenshots**
- N/A

**Desktop (please complete the following information):**
- N/A

**Additional context**
- N/A

**Comment by mattgodbolt** [comment]
Thanks for reporting this

**Comment by RabsRincon** [comment]
The culprit is https://github.com/compiler-explorer/compiler-explorer/blob/master/lib/storage/storage.js#L51 - But note that we don't actually know which character will be the last one of the hash - At least in the S3 case: https://github.com/compiler-explorer/compiler-explorer/blob/master/lib/storage/storage-s3.js#L100 . So our options are to either change what we map the `+` to on the Base64 alphabet, or use another encoding method

**Comment by apmorton** [comment]
I think all that needs to be done is to check if `subHash` ends with a `-` and if so extend it from the original full hash one character at a time until it doesn't end in a `-` when returning from the function you linked above.

At least in the s3 case - haven't look at any of the others.
