### ISSUE TITLE
[BUG] Open C++ tool, then change language to Python. Tool remains

### ISSUE THREAD

**Issue by steveire** [compiler-explorer/compiler-explorer#1991]
Open a c++ tool like clang-query in CE.
Then change language from C++ to Python.

The C++ tool and its output remains in the UI, even though the output now shows Python IR (I think).

https://gcc.godbolt.org/z/xcTs8f

**Comment by partouf** [comment]
This is actually mostly intentional, because some tools are also available for other languages (ldd, readelf, pahole etc) and clang-query also works for C, so if you switch between those they should probably stay. And if from python you switch back again to C++ the window will be useful again.

But I agree it should probably update properly and perhaps show the tool is disabled for that language or something.

**Comment by apmorton** [comment]
fixed in #1992
