### ISSUE TITLE
[REQUEST] Have insert key switch between insert and overtype text modes

### ISSUE THREAD

**Issue by 7keo** [compiler-explorer/compiler-explorer#1995]
**Have the insert key work like in most IDE's.**
Currently, the insert key seems to be ignored.  

**Desired behavior:**
When pressing the insert key the text editor should toggle between:

> * **Overtype Mode:** the cursor, when typing, overwrites any text that is present in the current location.
>* **Insert Mode:** the cursor inserts a character at its current position, forcing all characters past it one position further.
>
> \- from [wikipedia](https://en.wikipedia.org/wiki/Insert_key)

**Comment by mattgodbolt** [comment]
We use vs.code's editor, `monaco` as our editor. This might be an upstream issue: https://github.com/microsoft/vscode/issues/1012 - I don't think monaco supports this.

**Comment by partouf** [comment]
I noticed this during testing of the VIM keybindings, because I usually used insert to go into the text typing mode thingy, but hadn't realized this of course also applies to regular insert/overwrite mode. (mainly because I hate the feature, but that's just me)

But yeah, Monaco issue, and they're not in a hurry to support it.

**Comment by jeremy-rifkin** [comment]
I'll close this as not planned on our end for now
