### ISSUE TITLE
Support the 1f/1b gas notation?

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2034]
See #2033 and #2032 - we don't properly support numeric labels in the gas output. Though...it may not matter. I just tried to recreate the issue and: https://godbolt.org/z/jEYrPD it doesn't actually cause any issues as it would be unwise to have a "local" label outside of a function. And labels within functions aren't filtered out.

So, unless we start trying to "properly" understand label destinations and use them for anything but the nasty hacks for "is it used", this might actually be ok. Will mark this a question for discussion, but almost certainly we should close it.

**Comment by josephcsible** [comment]
> And labels within functions aren't filtered out.

It seems like they are in my testing, and I feel like this should definitely work within a function.

Input:
```c
void f(void) {
    __asm__ __volatile__(
        "nop\n"
        "1: # unused\n"
        "0: # unused\n\t"
        "jmp 0f\n"
        "1: # used\n\t"
        "jmp 1f\n"
        "0: # used\n\t"
        "jmp 1b\n"
        "1: # used\n"
        "0: # unused\n"
        "1: # unused\n\t"
        "nop"
        :
    );
}
```

Ideal output:
```assembly
f:
        nop
        jmp 0f
1: # used
        jmp 1f
0: # used
        jmp 1b
1: # used
        nop
        ret
```

Acceptable output:
```assembly
f:
        nop
1: # unused
0: # unused
        jmp 0f
1: # used
        jmp 1f
0: # used
        jmp 1b
1: # used
0: # unused
1: # unused
        nop
        ret
```

Actual output:
```assembly
f:
        nop
        jmp 0f
        jmp 1f
        jmp 1b
        nop
        ret
```

https://godbolt.org/z/v6fYxG

By the way, I found two possible workarounds for anyone who runs into this in the meantime:

1. Use "Compile to binary" so you can at least see the addresses being jumped to.
2. Compiling with Clang instead of GCC will convert the numeric labels to unique `.Ltmp` labels that are handled correctly.

**Comment by OfekShilon** [comment]
After recent fixes, the output today is the 'Acceptable output' mentioned above.   I think it's the best that can be done currently, suggest to close this.
