### ISSUE TITLE
Enable binary and execution support on gc compilers

### ISSUE THREAD

**Issue by elichai** [compiler-explorer/compiler-explorer#2051]
**Describe the bug**
Golang code compiled with `gc` doesn't execute, but one compiled with `gccgo` does.

**To Reproduce**
Just try to run anything for golang under `gc`

**Expected behavior**
It should run, like all other languages

**Link**
https://godbolt.org/z/sYYRhH

**Additional context**
The error is: 
```
Could not execute the program
Compiler returned: 2
Compiler stderr
flag provided but not defined: -Wl,-rpath,/opt/compiler-explorer/golang-1.14/go/lib
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
```

**Comment by apmorton** [comment]
This is by design, as we don't have compile to binary or execution support enabled on `gc` compilers. If you try to enable those options in a normal compiler pane you will see they are grayed out.

This is more a UI failing on our part than anything else - the execution pane doesn't prevent you from selecting compilers that don't support execution, and the server side doesn't validate things either.

Related: #1859, #2026

**Comment by partouf** [comment]
Execution with GC compilers has now been made to work, and those that still cannot will no longer be selectable in the execution pane.
