### ISSUE TITLE
I just realized this will slow down startup, maybe should get this from compiler-arguments.js ? can't do the same with clang/llc though

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2081]
I just realized this will slow down startup, maybe should get this from compiler-arguments.js ? can't do the same with clang/llc though

_Originally posted by @partouf in https://github.com/compiler-explorer/compiler-explorer/pull/1945_

**Comment by mattgodbolt** [comment]
Just capturing this for posterity.

**Comment by apmorton** [comment]
https://github.com/compiler-explorer/compiler-explorer/blob/cf7e0b029fb430e2f64c89ce99e8c9f088e5ba05/lib/buildenvsetup/buildenvsetup-base.js#L52

you can use `this.compiler.execCompilerCached` to avoid the (repeated) startup costs without too much refactoring.
If there is a way to avoid executing the compiler entirely, super - but if there isn't the cached compiler execution should be quite a bit less slow.

(It is by no means _fast_, since it basically boils down to an s3 request)
