### ISSUE TITLE
[BUG] Problem with PADDD opcode

### ISSUE THREAD

**Issue by mhahn-c** [compiler-explorer/compiler-explorer#2140]
Text is truncated:

...
The PADDQ and VPADDQ instructions add packed quadword integers from the first source operand and second source operand and store the packed integer results in the destination operand. When a quadword result is too<<<<<<<<<<<<<

**Comment by mattgodbolt** [comment]
Thanks! Can you share a snippet that produces this opcode so we can quickly repro and fix?

**Comment by mhahn-c** [comment]
https://godbolt.org/z/nedec3

Right-click on the `paddd`instruction to see opcode doc ... notice truncated text.

**Comment by apmorton** [comment]
This is all working "by design" currently.

We pull 5 paragraphs of text from the description, as defined here: https://github.com/compiler-explorer/compiler-explorer/blob/master/etc/scripts/docenizer.py#L27

In this particular case there appears to be a paragraph break in the middle of a sentence (probably unintentional), and it happens to land right on the boundary that we stop at.
![image](https://user-images.githubusercontent.com/63636/91647188-cea79480-ea25-11ea-8bb2-a594b19bb7cc.png)

We could:
- do nothing
- clarify the "For more information, visit xxx" disclaimer to something like "This description is intentionally truncated.  For more information, visit xxx"
- increase the paragraph limit and hope we don't introduce a similar bug in another instruction description
- see if felix can fix it upstream (although I doubt, since his site is also mechanically generated)
- try and introduce some fuzzy logic to read N more paragraphs if the one we would otherwise stop on doesn't end with a period

**Comment by partouf** [comment]
This was solved through the "For more information, visit ..." a while ago.
