### ISSUE TITLE
[BUG] PRs fail with JSON web token issues

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2154]
>  A JSON web token could not be decoded

`npm run ci-lint` seems to be the culprit.

**Comment by mattgodbolt** [comment]
Some random googling yields: https://stackoverflow.com/questions/52883268/a-json-web-token-could-not-be-decoded

**Comment by apmorton** [comment]
This is basically because PRs from outside contributors cannot access the secure environment that contains the private key for the eslint integration.

We can either:
- remove the integration entirely
- only run the integration for non-external PRs
- publish the private key for the integration app (at which point we would probably just switch back to using the upstream app on GitHub instead of our own)

**Comment by partouf** [comment]
I see the unittests still do run, so that's good. But linting is quite important in detecting errors in JS code, so I don't really like that they're not running when submitting PR's.

So I would prefer option 3 in this case.

**Comment by partouf** [comment]
Although if there's a way to still run a linter (just npm run lint?) in case of external PR's, and run ci-lint for internal that would be Ok too. Perhaps we can make a scripty thing that sees if the token is there and makes a choice based on that?

**Comment by partouf** [comment]
things have changed a bunch since 2020, this is no longer relevant
