### ISSUE TITLE
[BUG] RESTful API changed

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2183]
The RESTful API doesn't work as [documented](https://github.com/compiler-explorer/compiler-explorer/blob/master/docs/API.md):

```
~ $ curl 'https://godbolt.org/api/compiler/g63/compile?options=-Wall' --data-binary 'int foo() { return 1; }'
<!DOCTYPE html><html lang="en"><head><base href="/"><title>Error 404</title></head><body style="background-color:#f2f2f2;display:flex;align-items: center;justify-content: center;"><div><a href="/" title="Go to main site"><svg class="normal" height="50" width="165"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 894 270">
```

The automated uptime checks use this, so we'd need to change them or put back existing behaviour.

**Comment by partouf** [comment]
Pulling wireshark out of the closet, curl is doing something that doesn't end up in any express route it seems...

**Comment by partouf** [comment]
```
POST /api/compiler/g101/compile?options=-Wall HTTP/1.1
Host: 192.168.4.192:10240
User-Agent: curl/7.65.3
Accept: */*
Content-Length: 23
Content-Type: application/x-www-form-urlencoded

int foo() { return 1; }
```

I think the problem here is that Content-Type is unexpectedly x-www-form, while there are no form fields in the body.
I added a form field parser to automatically populate request.body with the variables that are posted by forms (noscript). Here https://github.com/compiler-explorer/compiler-explorer/commit/32aadc90e7ec957f7d2f4da3d7f2e493515fb8d1#diff-0364f57fbff2fabbe941ed20c328ef1aR692

I'll fiddle around with settings and see if we can support both situations. (Though I think what curl does falls under the UB category)

**Comment by mattgodbolt** [comment]
Oh that's super weird! I'm sure we can change `curl` but I wonder what the uptime check thing uses?
![Screenshot from 2020-09-04 16-35-50](https://user-images.githubusercontent.com/633973/92286460-bb387580-eecc-11ea-822e-ff84b9b67912.png)
