### ISSUE TITLE
[REQUEST] Rewrite AsmParser in C++

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2199]
I think this might be the best way to improve load and speed during reading assembly.
I know it will be hell and crazy and back, but maybe CTRE can help us with the job.

If anyone wants to tackle this thing, shout out, throw an early work-in-progress PR or repo, and I'm sure we'll have something useful to say about any issues one might have.

(the best tactic is probably to take in stdin and output to stdout and have no file IO)

All the overrides we can handle later when there's a proper base application to handle this.

**Comment by mattgodbolt** [comment]
It would be a trip to have this to also support the "standalone asm cleaner" #1308 .

Would make the project a lot more sensitive to OS/build requirements (e.g. windows, ARM installs etc). Our native code needs to build cleanly and "just work" out of the box when folks `git clone` and then `make`, but that ought to be achievable. We know they _probably_ have a C++ compiler, but what version it is... Also our friends from other languages might not have a very recent C++ compiler on their system.

So! Definitely a good thing to do. Do we have some example "torture" asm files that take a while to process? I'll bet the main issue is that we use regexes at all instead of actually writing a real parser :D

**Comment by partouf** [comment]
I think it might be acceptable to at least have the current version of the JS parser - for as long as we can maintain it. But there to be some flexibility that we can set the .amazon. version to be an executable.

**Comment by mattgodbolt** [comment]
That's an excellent point: love it: thanks!
