### ISSUE TITLE
add support for cuda-nvcc and vexCL Library

### ISSUE THREAD

**Issue by cppchedy** [compiler-explorer/compiler-explorer#221]
add Support for CUDA's nvcc and OpenCL. writing verbose GPU stuff isn't cool, so i recommend vexCL library support.

**Comment by mattgodbolt** [comment]
Thanks for filing this.  Having no experience with either nvcc or OpenCL, how might this be integrated with Compiler Explorer? The output of both doesn't appear to be assembly instructions.

**Comment by cppchedy** [comment]
as can be seen from [here](http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#cuda-compilation-trajectory__cuda-compilation-from-cu-to-cu-cpp-ii) nvcc can produce object file compatible with gcc(linked with g++(ld) as done [here](http://stackoverflow.com/questions/9421108/how-can-i-compile-cuda-code-then-link-it-to-a-c-project)). dummy idea, just grab that object file and disasm it. I hope it work with no problem.(truly don't know if it will work hope so)

 using  opencl is as easy as using any other library, the only requirement is to link (check  [Stackoverflow](http://stackoverflow.com/questions/16977216/opencl-compile-on-linux?rq=1) )libOpenCL.so/dll(depend on platform linux/windows) using  gcc. we don't need any special tool . so same idea, we can directly output assembly code or disassemble from binary.

[VexCL](https://github.com/ddemidov/vexcl) is a header only library. you can checkout [doc](http://vexcl.readthedocs.io/en/latest/initialize.html) and this [video](https://www.youtube.com/watch?v=W8onyk2Rraw).

Recup: 

- for  Cuda nvcc tools, with the above proposition, we can only ouput assembly listing after getting final binary or object file.
- for openCL I think we can handle both: outputting direct assembly from compiler or from binary.

I did not test any of these proposals but I don't see why they won't work.

 **note**: if you use ubuntu(and you have nvidia GPU) ,you can get opencl  through sudo apt-get install nvidia-opencl-dev and play with it. to start, use this tutorial [opencl-tuto](https://bitbucket.org/Anteru/opencltutorial/src/1c2025779d60?at=default) and check the cmakelists.txt and main.cpp to see the mechanics.

**Comment by haneefmubarak** [comment]
Unfortunately, I don't think that will actually work out correctly. AFAIK, nvcc generates PTX bytecode based on the set CUDA target arch. At runtime, the PTX bytecode is delivered to the running NVidia driver, which actually recompiles the PTX to the specific assembly language of the particular graphics card(s) that you have.

In other words, if you get this to work, you'll end up with some x86(_64) code for the host side code, but the device side code will be relatively obscure PTX, which while readable, isn't really designed to be analyzed at that stage (performance analysis given only PTX can be extremely unpredictable and counterintuitive) and isn't designed to be written by hand either (reading the generated PTX code would not likely help you in writing high performance PTX code).

---

That being said, generating assembly from OpenCL (if only targeted to run on the host) may be more viable, since [in theory] that should just generate normal assembly, albeit with a lot of SIMD instructions.

**Comment by cppchedy** [comment]
thanks for the clarification! 
can you give an example in witch opencl will ouput sth other than normal assembly?
<hr>

I hope at least we get OpenCL support than.

**Comment by dbeurle** [comment]
I think the argument that PTX doesn't provide insight into the performance of the code and therefore isn't useful doesn't really paint the complete picture.  Not everyone can inspect x86 assembly and determine the runtime performance, that's why we benchmark it.

Since CUDA supports some subset of the C++11/14 language, it is possible to write template kernels and device functions.  Here PTX inspection is useful to see what disappears and if some abstraction generates the expected number of instructions.  This is still useful regardless of how it is further compiled to the instruction set specific to the compute device.

For example:

```cpp
__global__ void test_kernel(int const i, int& out)
{
    out = i * 2;
}
```
complied with `nvcc -I/usr/include/cuda -ptx -c -g cuda_ptx_test.cu ` gives
```
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-23083092
// Cuda compilation tools, release 9.1, V9.1.85
// Based on LLVM 3.4svn
//

.version 6.1
.target sm_30
.address_size 64

	// .globl	_Z11test_kerneliRi

.visible .entry _Z11test_kerneliRi(
	.param .u32 _Z11test_kerneliRi_param_0,
	.param .u64 _Z11test_kerneliRi_param_1
)
{
	.reg .b32 	%r<3>;
	.reg .b64 	%rd<3>;


	ld.param.u32 	%r1, [_Z11test_kerneliRi_param_0];
	ld.param.u64 	%rd1, [_Z11test_kerneliRi_param_1];
	cvta.to.global.u64 	%rd2, %rd1;
	shl.b32 	%r2, %r1, 1;
	st.global.u32 	[%rd2], %r2;
	ret;
}
```
which is intermediate assembly, but enough to draw some limited conclusions (e.g. integer multiplication by two is a left shift).  This is a silly example but demonstrates the value of including this - if only for educational purposes.

Clang can also generate PTX (https://llvm.org/docs/CompileCudaWithLLVM.html), so it's a matter of enabling that back-end in the compile options and pulling in `nvcc` and friends (yuck) for comparison.

The PTX manual provided by NVIDIA is here:
http://docs.nvidia.com/cuda/parallel-thread-execution/index.html

Thoughts?

**Comment by giordi91** [comment]
Bit late to the party, but as far as I know there are multiple ways to run cuda, one is to distribute PTX that gets converted at runtime, for your specific hardware, but you can also generate FAT binaries, meaning you can compile with specific architectures, (multiple ones aswell) at runtime the driver will pick up the correct code if available or will error. There is a utility called cudaobjdump that lets you dump actual disassembly, not IR. I played with the PTX version on compiler explorer and is great, would be good to get actual disassembly aswell.
https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html

**Comment by dbeurle** [comment]
@mattgodbolt Thanks for the CUDA support!  I had a play around and it's pretty good.

Would it be better to open an additional issue for OpenCL support?  Clang can handle OpenCL through
```
clang++ -std=CL2.0 -target amdgcn-amd-amdpal-opencl -mcpu=gfx900 -S -c C_row.cl -O3
```
for an amdgpu target.

**Comment by he-sk** [comment]
OpenCL support would also be helpful for CPU targets, i.e., Intel, AMD, or ARM. I think that the Intel OpenCL driver calls icc at some point. A real benefit of the integration with this tool would be that you could see how the Intel compiler autovectorizes the OpenCL code.

**Comment by mattgodbolt** [comment]
I'm looking for a CUDA expert to take on this kind of stuff. I feel like I'm playing telephone with folks trying to understand what people want :) As a non-CUDA non-PT person with little free time other than to (just about) keep the wheels turning on the regular site I need help form this side. Thanks!

**Comment by mhammerc** [comment]
Hello!

Sorry for the late answer.

I am not a CUDA expert, I am still learning on a regular basis!

As I can see, there already is a good support for CUDA, compiling to byte code. That is fine!

What I don't know is how this bytecode is compiled to the specified compute capability. Each compute capability have different features and different ways of doing things. For example (I may be wrong): A 256 bytes copy may be done in one instruction or two instructions.

For advanced technical programmers, maybe they may find interest to look at the bytecode (the generated textual instructions) *and* the actual instructions generated for a specific compute capability. I have to look at this, but I think it is raw binary code, which is undocumented.

Finally we may add the `vexCL` library as asked on the first message. CUDA recently announced support for some STL containers inside CUDA code (if I am not mistaken), which may makes `vecCL` obselete but it is not a reason to not add the library.

On OpenCL side, I have yet not clue on how it works inside. I try to look at it, and learn what "bytecode" or instructions it creates, and if there are differences if compiling for nVidia, AMD and Intel.

Again I am not a CUDA experienced user.

**Comment by eyalroz** [comment]
I believe this issue should be closed, as CUDA compilation is now supported (but see my issue #1856). A separate issue can be opened regarding vexCL if that's relevant (I'm not sure); and for OpenCL, which is quite relevant.

**Comment by jeremy-rifkin** [comment]
I think we now support both CUDA and OpenCL
