### ISSUE TITLE
[REQUEST] nasm fails when compiling with -fbin

### ISSUE THREAD

**Issue by sqrtroot** [compiler-explorer/compiler-explorer#2221]
**Describe the bug**
When compiling a binary with `-fbin` to just get the binary output nasm fails because it's incompatible with the `stabs` debug mode.

**To Reproduce**
- Create a new assembly file
- add `-fbin` to compile flags

**Expected behavior**
When either selecting compile to binary or `-fbin` are selected flags for setting debug mode should be removed.

**Link**
https://godbolt.org/z/qPWbfj

**Comment by partouf** [comment]
Without an example of what you might want to put into nasm when doing this, we won't be able to test if anything of this will actually work. Can you provide an example?

**Comment by sqrtroot** [comment]
Sorry for the late response:
A code example, writing your own elf header. Locally this produces the following output:
![](https://user-images.githubusercontent.com/6583557/94849962-80bbed00-0426-11eb-93ba-a90ab4065df2.png)
but it doesn't want to compile on godbolt https://godbolt.org/z/zxEs94

**Comment by partouf** [comment]
Got it, thanks for the example!

**Comment by partouf** [comment]
Changes for this are now live, if you suppply `-f bin` it will override all the standard parameters. Note though that -fbin doesn't result in actual disassembly, because the disassembler that we use (objdump) does not support that. However you can of course see any errors in your assembly, and you can now also activate the readelf tool to maybe read details about the headers of the binary.
