### ISSUE TITLE
[REQUEST] Change recommended Make

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2250]
In a couple of places I think, and at least the readme, it is said to use `make` to start CE locally. But make literally takes forever / is less verbose because webpack is done first.

Perhaps it's better to recommend `make dev` instead?

**Comment by partouf** [comment]
And perhaps include the Windows npm equivalent (well, except supervisor). `npm run dev`

**Comment by partouf** [comment]
Talking about supervisor, I just noticed this error:
`Error: ENOSPC: System limit for number of file watchers reached`

**Comment by mattgodbolt** [comment]
Jetbrains products moan about this too, they say to bump

```
fs.inotify.max_user_watches = 524288
```

in `/etc/sysctl.conf`. We can also try and reduce the number of files supervisor is actually looking at, more helpfully (e.g. stop it tracking `node_packages`.)

I also agree the `make` should change and/or we should change the default make target to `dev` instead.

**Comment by apmorton** [comment]
I guess we need to clarify what it means to "run CE locally".

If you are running it locally to test some changes `make dev` is superior because it starts up faster.

If you are running your own CE instance locally on an ongoing basis, `make` (IE `make run`) is a better choice because it runs webpack with optimizations enabled.

Unfortunately it runs webpack _every time_, regardless of whether any files change - so that could definitely be improved.

**Comment by partouf** [comment]
This was changed a while ago
