### ISSUE TITLE
[BUG] Syntax highlighting misses escaped newlines

### ISSUE THREAD

**Issue by mrvn** [compiler-explorer/compiler-explorer#2288]
**Describe the bug**
A c++ comment ending in \ continues on the next line because the newline is escaped. The syntax highlighting misses that fact.

**To Reproduce**

Type in:

    int main(void) {
        int beep = 0;
        // Oh no a shark______/\
        beep = 1337;
        return beep;
    }

The "beep = 1337;" is colored like real code.

**Expected behavior**

"beep = 1337;" should be colored as a comment.

**Link**

https://godbolt.org/z/ocWrha

**Comment by mattgodbolt** [comment]
Unfortunately Compiler Explorer doesn't support sharks...

:grinning: :wink: 

More seriously this is an issue with the editor we use (Monaco)'s C++ mode - https://github.com/Microsoft/monaco-editor - we're currently on version 0.20, but it seems this issue is still unfixed there: https://github.com/microsoft/monaco-editor/issues/1184

**Comment by partouf** [comment]
this was fixed for comments, no idea when, but fixed nonetheless
