### ISSUE TITLE
[BUG] MIPS compilation bug

### ISSUE THREAD

**Issue by uncttao** [compiler-explorer/compiler-explorer#2311]
**Describe the bug**
MIPS compilation produces problematic assembly code.

**To Reproduce**
Use `C` as source, and enter the following code.
```
void main() {
  fib(10);
}

int fib(int n) {
  if (n == 0)
    return 0;
  if (n == 1)
    return 1;
  return fib(n - 1) + fib(n - 2);
}
```
Use `MIPS gcc 5.4` as the target (no arguments), it produces the following assembly.
```
main:
        addiu   $sp,$sp,-32
        sw      $31,28($sp)
        sw      $fp,24($sp)
        move    $fp,$sp
        li      $4,10                 # 0xa
        jal     fib
        nop

        nop
        move    $sp,$fp
        lw      $31,28($sp)
        lw      $fp,24($sp)
        addiu   $sp,$sp,32
        j       $31                   ### bug? ###
        nop

fib:
......
```

**Expected behavior**
The line `j       $31` should be `jr       $31`. It should be `jr` not `j`.

**Link**

**Screenshots**

**Desktop**

 - OS 
 - Browser 
 - Version 

**Additional context**

**Comment by mattgodbolt** [comment]
[ https://godbolt.org/z/Y4eqW6 ]

Hi @uncttao thanks for the message. Compiler Explorer shows the output of the compilers, so if there's a bug in the compiler then it will show this.

I ran the compiler directly outside of Compiler Explorer: 

```
$ /opt/compiler-explorer/mips/gcc-5.4.0/mips-unknown-linux-gnu/bin/-gcc -S -o - test.c

...
main:
...
        .frame  $fp,32,$31              # vars= 0, regs= 2/0, args= 16, gp= 8
        .mask   0xc0000000,-4
        .fmask  0x00000000,0
        .set    noreorder
        .set    nomacro
        addiu   $sp,$sp,-32
        sw      $31,28($sp)
        sw      $fp,24($sp)
        move    $fp,$sp
        li      $4,10                   # 0xa
        jal     fib
        nop

        nop
        move    $sp,$fp
        lw      $31,28($sp)
        lw      $fp,24($sp)
        addiu   $sp,$sp,32
        j       $31
        nop
...
```

And this appears to be the output from the MIPS GCC compiler. I'm sorry we don't have a newer MIPS GCC available to check against, but if it's a bug, I'd imagine it has been fixed by now.

That said, it seems the compiler generates `j` for jump to registers anyway: https://stackoverflow.com/questions/59130450/why-did-the-compiler-put-an-instruction-after-the-mips-j-instruction-that-retu for example shows the compiler using `j`. I suspect GCC uses `j` and infers the `r`-ness by seeing it has a register operand.

**Comment by mattgodbolt** [comment]
Oops I just realised the link I used was itself quoting Compiler Explorer, so the argument is circular. Let me see if I can find something more concrete.

**Comment by mattgodbolt** [comment]
From https://www.cs.umb.edu/cs641/MIPscallconvention it seems that `j $reg` is just how GCC wants it:

```
Unoptimized: set up stack, use it all the time (easy for debugger to understand)
....
        lw      $3,8($fp)         <-- load i from stack
        lw      $2,28($fp)        <-- load arg1 from stack (x)
        addu    $2,$3,$2          <-- compute x + len = return value in v0
        move    $sp,$fp
        lw      $fp,16($sp)       <-- restore caller’s fp
        addiu   $sp,$sp,24        <-- pop off the frame
        j       $31          ```
