### ISSUE TITLE
[BUG] C code doesn't support "filter library"

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2350]
Pick C, note that "filter library" code is greyed out, but it...should work.

**Comment by partouf** [comment]
No idea how to actually test this. In what situations can this happen in C?

**Comment by partouf** [comment]
Works for MSVC though because it has some wrappers for external functions like printf , but on Linux they're just external calls. Hmm.

It might work with `-static`, but there are some bugs in binary mode concerned to that afaik, so it's not doing anything there either. (and static is linking stage thing, so doesn't show up in normal asm mode).
