### ISSUE TITLE
[BUG] msvc "latest" has no STL

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2448]
```cpp
#include <vector>
```

Fails to compile on MS compiler explorer: https://godbolt.org/z/qTavfY (and https://www.godbolt.ms/z/38ipLK )

**Comment by partouf** [comment]
Latest doesn't compile at all, I think this will fix itself once latest is fixed.

**Comment by robindegen** [comment]
Seems fixed now if I shift+f5 refresh.

**Comment by partouf** [comment]
This was fixed by latest being fixed. However the compiler id changed, so the link now shows a different compiler.
(https://godbolt.org/api/shortlinkinfo/qTavfY -> compiler id `vcpp_(latest)_x64`)
New id from https://www.godbolt.ms/api/compilers is `vcpp_v19_latest_x64` - I think this is probably more correct.

Considering this has been only a few days online, I think it's fine there's not an alias.

**Comment by mattgodbolt** [comment]
100% agree Partouf, thanks
