### ISSUE TITLE
Font sizes differ between output window and editor (same pt size appears different size)

### ISSUE THREAD

**Issue by tawmoto** [compiler-explorer/compiler-explorer#2457]
Enter the site for the first time or reset the layout to default.
The code font is too small and the output font is too big.

Thanks

![image](https://user-images.githubusercontent.com/35702340/109682240-e7386900-7b86-11eb-84a0-74063583f007.png)

**Comment by mattgodbolt** [comment]
Hi @tawmoto - obviously font size is a personal choice. I set the default font size to be 14pt, which is larger than most websites (indeed, comparing the default font size of CE against the font size that I'm typing this comment in to, CE's font size is bigger).

The size of the font is configurable for this reason. Out of interest, what font size would you pick?

**Comment by tawmoto** [comment]
Hi @mattgodbolt , thanks for answering, big fan here. :-)
My concern is that the output font (right part of the pic) is huge compared to the code editor font(left part of the pic). See my attached photo, so basically persons like me always increase the size of the editor font and decrease the size of output.

Is there a reason for this?
Thanks

**Comment by mattgodbolt** [comment]
Got it: right - so it's not so much the actual size, rather the relative size!

That makes sense; it's not really on purpose that the output is that much bigger, no! It just turned out that way and I suppose I got used to it. I think it's the different fonts used: the editor windows use Monaco, but the output pane is regular HTML.

**Comment by tawmoto** [comment]
Great, thanks for understanding :)

**Comment by apmorton** [comment]
Did some digging and it looks like monaco is interpreting the font size as pixels, while the output window is interpreting it as points.

It is likely points was the original intent (since it is explicitly being appended to the number for output window), but maybe using pixels is the better tradeoff here since it doesn't look like monaco has a way to accept points.

**Comment by mattgodbolt** [comment]
Thanks for the diagnosis, @apmorton - I agree with you there. It would be (somewhat) of a breaking change to interpret the font size in pixels for the non-monaco stuff but I think it's worth doing to unify everything. Only a few folks would notice, maybe @lefticus mostly :) Jason, your defaults output window might get a bit of a smaller font...

**Comment by tawmoto** [comment]
@mattgodbolt and another problem, when I set the size 16 for the editor window and 16 for the output window, the output window font is a lot bigger, which is a bit strange, it's the same number 16 :-) thanks
