### ISSUE TITLE
How to run on my local computer

### ISSUE THREAD

**Issue by thecodersatish** [compiler-explorer/compiler-explorer#2469]
Bro can anyone please tell me step by step how to run this on my local computer

**Comment by mattgodbolt** [comment]
Hi there! Looks like we need to clean up our docs a little, but the "how to" is in the README: https://github.com/compiler-explorer/compiler-explorer/#developing

If you're on Linux it boils down to:

* install a stable version of `node.js`  - we use and need at least version 12, but newer ones should work too. ( https://nodejs.org/en/ )
* run `make`
* After a short pause while dependencies are installed and packages are made, you should get Compiler Explorer running on port 10240 on your compiler, so visit https://localhost:10240 in your browser.

A while back @lefticus made a video on how to run locally: https://www.youtube.com/watch?v=I2cKVRzJhS0 - that might help too.

**Comment by mattgodbolt** [comment]
Please let us know if that covers your use cases.

**Comment by thecodersatish** [comment]
Hii im not using linux im using windows

**Comment by partouf** [comment]
For Windows we have the doc https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/WindowsNative.md - but currently it's quite MSVC specific. It very much depends on which compilers you want to get working in CE.

**Comment by thecodersatish** [comment]
hii i have followed all the steps mentioned in the above link but it's showing an error while running npm start

**Comment by thecodersatish** [comment]
on compiler explorer im getting only python not all languages and even python is also not working its showing following error
Internal Compiler Explorer error: Error: spawn python3.8 ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:276:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
Compiler returned: -1

**Comment by mattgodbolt** [comment]
Hi @thecodersatish - Compiler Explorer does not include all the compilers for all the languages. By default we try and find installed compilers with a very cheesey hack.

In order to point Compiler Explorer at the compilers you've installed you'll need to configure it. Configuration is not quite as easy as we'd like, but essentially means creating a `etc/config/c++.local.properties` file with some information in it to point it at your own compilers. Some information on this is at: https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingACompiler.md#configuration

For Linux we have many of the open source compilers built and configured and available; but not for Windows, unfortunately. 

I hope this helps a little.
