### ISSUE TITLE
[REQUEST] Add optimization report functionality to icx

### ISSUE THREAD

**Issue by rscohn2** [compiler-explorer/compiler-explorer#2484]
ICX/IFX (Intel oneAPI) was recently added. Since it is llvm-based, I assume it can have the same optimization report functionality as other LLVM-based compilers in compiler explorer.

Adding an issue as a reminder for me to do it later. If someone else wants to do it, let me know.

**Comment by rscohn2** [comment]
Here is an example for clang: https://godbolt.org/z/7PE7q8

**Comment by partouf** [comment]
I was wondering about this, but since I don't know anything about the OPT view I didn't feel confident to test.

I think we have some automatic detection for the appropriate compiler parameters, but they seem to not be detected, so there would have to be a change to that. Or maybe if we change the compilerType to clang, it might already work...

**Comment by rscohn2** [comment]
I just tried setting the compilerType, but it did not work. Where should I look in the code for the detection?

**Comment by partouf** [comment]
Over here, I believe
https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/compilers/argument-parsers.js#L129

**Comment by partouf** [comment]
Oh, curious that this issue is still open. This has been fixed for more than a year.
