### ISSUE TITLE
[BUG] Monaco 0.23 upgrade breaks Safari 13

### ISSUE THREAD

**Issue by apmorton** [compiler-explorer/compiler-explorer#2529]
Safari 13 throws: `SyntaxError: Invalid regular expression: invalid escaped character for unicode pattern` after d2ccba892604b23ddcc5fd710f145304c985a5f4

I was able to use BrowserStack with a dev build of CE to locate the error to here:
![image](https://user-images.githubusercontent.com/63636/112795142-1501b800-9036-11eb-9068-39a69f310d53.png)

Which then traces back to monaco:
```
$ grep -rl "SnakeCaseAction" *
node_modules/monaco-editor/min-maps/vs/editor/editor.main.js.map
node_modules/monaco-editor/esm/vs/editor/contrib/linesOperations/linesOperations.js
node_modules/monaco-editor/dev/vs/editor/editor.main.js.map
node_modules/monaco-editor/dev/vs/editor/editor.main.js
node_modules/monaco-editor/min/vs/editor/editor.main.js
```

**Comment by mattgodbolt** [comment]
Oh blast :( Thanks @apmorton I should have checked. You mention some browser thing; would be ace for us to have headless tests or something that at least load up the page for sanity..

**Comment by mattgodbolt** [comment]
In the linked bug, @alexdima said:

> This appears to work fine in Safari 14, so if you have found a workaround for Safari 13, then I don't think we would want to do more on our side.

which seems to put the onus on us post-processing the regexes somehow to make them compatible.

**Comment by mattgodbolt** [comment]
with reference to https://github.com/microsoft/monaco-editor/issues/2345#issuecomment-802596035

**Comment by apmorton** [comment]
For what its worth, safari 13 is EOL and hasn't been patched since July 2020.
I am perfectly happy letting it stay broken.

**Comment by mattgodbolt** [comment]
Ok! Phew. I had no idea it was so old. We /do/ support a lot of things (e.g. we still use `var` in the JS side instead of `let` and `const`).

Looking at the versions used in the last year (google analytics, so biased to those who allow it):

![Screenshot from 2021-03-29 09-19-31](https://user-images.githubusercontent.com/633973/112850743-e86a9200-906f-11eb-8170-b0087ef896b9.png)

**Comment by mattgodbolt** [comment]
Still a bunch of folks. In the last month it's dropped off though, with the sum of 12.* and 13.* users adding up to 5% of Safari users.

**Comment by alexdima** [comment]
Actually this will get fixed with the next monaco editor release. Here is the PR that fixed it -- https://github.com/microsoft/vscode/pull/118400/files#diff-dde3b56145713053f086e5ce1fcea39c4cb171d4555b6ab91256c7cf2b39e9afR1061

**Comment by mattgodbolt** [comment]
Oh wow! Thanks @alexdima !

**Comment by tigerw** [comment]
I'm also seeing the same issue on Edge 44.19041.423.0

SCRIPT5674: SCRIPT5674: Invalid regular expression: invalid escape in unicode pattern

**Comment by apmorton** [comment]
Edge 44 is the legacy EdgeHTML based browser that has not been maintained for over a year, and is no longer supported by monaco.

The newer chromium based edge is fully supported.

**Comment by mattgodbolt** [comment]
Moving Waterfox Classic bug here:

Describe the bug
Source editor, assembler output panes don't appear

To Reproduce

Open www.godbolt.org with Waterfox Classic 2021.03 (64-bit)

Expected behavior
Source editor, assembler output appear.

Link
godbolt.org

Screenshots
See MrAlex94/Waterfox#2052

Additional context

SyntaxError: invalid identity escape in regular expression  vendor.v4.e355c14b4154f354d058.js:2:2630816
appears in the Web Console

**Comment by partouf** [comment]
Good issue to test https://github.com/compiler-explorer/compiler-explorer/issues/2675 before it gets fixed by monaco
