### ISSUE TITLE
[REQUEST] Macro expansion for Rust

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#2568]
Similar to Clang's "AST output" and "IR output", it would be nice to have "Macro expansion output" for Rust via `--pretty=expanded`.

The Rust playground has support for it under "Tools".

**Comment by RubenRBS** [comment]
Hi Miguel. Sorry that nothing was said on here about this group of requests! The one main thing blocking this (and the rest) is that it would need to be a something that would need to show up only for Rust compilers. 

I have some ideas on how to do that so that it's still usable (And not our usual way of sticking everything in the UI!) It might take me a bit, but I'll try!

Again, sorry about the radio silence

**Comment by ojeda** [comment]
No problem at all -- it is definitely not a priority :)

Perhaps then it would be best to take time to design first about a way to have custom options per-compiler instead.
