### ISSUE TITLE
[REQUEST] Support linking for asm

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2577]
Was asked over email if we supported it, and said no: but https://godbolt.org/z/v8vM6Y91n could probably be made to link and work ok, if we supported linking of asm output pre-execution.

**Comment by partouf** [comment]
So what exactly should be linking with?

**Comment by mattgodbolt** [comment]
I _think_ just running `ld` on the `.o` will make an executable.

**Comment by partouf** [comment]
Wanted to document the steps that I took to get this working, but quickly found out this process probably isn't friendly for new users - so maybe this writedown is irrelevant:
* Install a GCC and Nasm with ce_install
* Copy `etc/config/assembly.amazon.properties` to `etc/config/assembly.local.properties`
* Verify Assembly is available and nasm/gas works (`make dev` and check `http://127.0.0.1:10240/`)
* Change `supportsExecute` to `true` in the properties file
* Copy functions `buildExecutable` and `getExecutableFilename` from `lib/base-compiler.js` to `lib/compilers/assembly.js`
* Write new implementation that executes this.runCompiler (note async function) and follows it up by a new execution that calls LD in combination with the objectfile and outputs it to a new filename that is named by `getExecutableFilename` (should not be original implementation).
* Figure out how LD even works... (apparently you need to pass `-m elf_i386` for emulation of x86 instead of passing `--oformat elf32-i386`)
* Experiment and test until things are Ok

See for implementation https://github.com/compiler-explorer/compiler-explorer/pull/2581

**Comment by partouf** [comment]
Btw this is now live (since 2 days ago)
Nasm -> https://godbolt.org/z/44zacY5xv
Clang -> https://godbolt.org/z/KcqP5TP8b
GCC -> https://godbolt.org/z/jnzr4jGn7

**Comment by mattgodbolt** [comment]
Amazing! Thanks!!! Will let the OP know :)

**Comment by BaseMax** [comment]
Many thanks to Patrick, and Matt. :+1:
