### ISSUE TITLE
Make issues everywhere

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2595]
The last couple of months we've been hearing more and more issues with `make` and it not doing enough work to start CE.

Issues are always resolved by "just doing" `npm i` + `npm run` dev/start.

### Mac issues
* Not sure what the problem is here, it doesn't seem to npm install, the rest appears to work.

### Node 15
Recently we had someone with node 15 on arch linux that had 2 issues after a `make`:
* Supervisor was not installed
  * Not sure how to resolve this
* The line with npm install --only=dev doesn't work
  * https://github.com/compiler-explorer/compiler-explorer/blob/a194b5a591658d69eba5a9f12d7b5e596d82c561/Makefile#L39

### Other issues after updating node/npm
* `webpack-cli/bin/cli.js`: No such file or directory
  * It seems webpack-cli is not installed (so also the dev bits) with `make`

**Comment by mattgodbolt** [comment]
I suspect somethin gin a newer `npm` wrt to the way dev and prod deps work. our makefie is a bit funny about that for reasons I forget now :(

**Comment by saurabhjimmy** [comment]
Hi
I've also faced node related issues but was easily able to circumvent this with switch to v12.22.5 LTS in nvm. 
Probably best not to make too many changes and reverting back to supported config.

I started going a bit deeper and have found another issue; wanted to check if you've already seen this as well.  
I think it's not exactly an error with webpack packages but with the 'copywebpack' plugin itself, which manifests into files not being copied correctly and make failing.

With the update to the 6.x major version came a breaking change: instead of just passing the array with the config patterns directly to the CopyWebpackPlugin constructor, your now have to wrap it in the patterns property of an object and pass that.

Old syntax:

    new CopyWebpackPlugin(
      [
        { from: 'src/xxx.ext', to: 'dist/xxx.ext' },
        { from: 'src/yyy.ext', to: 'dist/yyy.ext' }
      ]
    )

New syntax:

    new CopyWebpackPlugin(
      { 
        patterns: [
          { from: 'src/xxx.ext', to: 'dist/xxx.ext' },
          { from: 'src/yyy.ext', to: 'dist/yyy.ext' }
        ]
      }
    )



-Thanks
