### ISSUE TITLE
[BUG] PEGTL "trunk" is not actually "trunk"

### ISSUE THREAD

**Issue by d-frey** [compiler-explorer/compiler-explorer#2778]
When selecting the PEGTL in the library section, I get two options: "2.8.0" (deprecated, can be removed (I'm one of the authors)) and "trunk". But "trunk" then only adds an old version of the PEGTL, as can be seem from here: https://godbolt.org/z/c1jdY74j3

The output is "3.0.0" where it should show "3.2.1" (as of now, will change in the future). Also, including taoJSON doesn't work due to the old version of the PEGTL.

Additionally, if possible, selecting the "trunk" from "taoJSON" should automatically select "trunk" from the PEGTL as well, as taoJSON requires the PEGTL to be present.

**Comment by partouf** [comment]
It seems we messed something up when changing installers. I'll try to fix it.

**Comment by partouf** [comment]
I have fixed it.

Concerning 2.8.0, we currently don't have a way to hide older versions without breaking links people might be still having, so we can't remove it at the moment.

**Comment by d-frey** [comment]
Thank you for the super-quick fix! I just confirmed it works!

**Comment by partouf** [comment]
> Additionally, if possible, selecting the "trunk" from "taoJSON" should automatically select "trunk" from the PEGTL as well, as taoJSON requires the PEGTL to be present.

Concerning this, there's no way to do this either. This is because there are too many conditions and situations to consider when having to support this. Usually people tend to include a version themselves into the repo, but I don't really recommend that either.

I think the best thing to do is to include a helpful text about this in the description and create example shortlinks. Happy to help with that if you want that.

**Comment by d-frey** [comment]
Thanks, but I guess that won't be necessary. The users will figure it out (as the error message is quite clear) and it just needs to work - which it does now.

**Comment by partouf** [comment]
Got it.
