### ISSUE TITLE
Can you add the rust futures library so we can play with ‘—edition 2018’ async code?

### ISSUE THREAD

**Issue by wsgeek** [compiler-explorer/compiler-explorer#2823]
Or better yet I can do it if someone shows me how — happy to help!

Thanks all

**Comment by supergrecko** [comment]
To add the futures crate we'd have to support Cargo and crates first. There is a discussion regarding this in #2523

**Comment by RubenRBS** [comment]
Hi! Thanks for requesting the library. As @supergrecko said, library support for Rust is supper tricky for us and it's something we're actively seeking, but due to how we currently setup Rust in the live site, it's not something we can easily do, sorry about that :/

I'll make sure that once we do, futures is one of the crates we support! I'll close this in favour of the mentioned issue to keep proper track of all the requests
