### ISSUE TITLE
[REQUEST] Jump back after going to label

### ISSUE THREAD

**Issue by Merovius** [compiler-explorer/compiler-explorer#2825]
**Is your feature request related to a problem? Please describe.**

When inspecting the generated assembly, I'd like to follow a conditional jump to see what happens in that case. Once I understand that, I want to continue reading the original code.

**Describe the solution you'd like**

I'd like a keyboard-shortcut or button in the UI to go back to the previous view. That is, when executing an action like "jump to label" or "view linked code" (but not when scrolling manually or by pressing up/down or page-up/down), the current view should be pushed to a stack and by pressing some shortcut or button, the topmost view state on that stack should be restored.

AFAICT `monaco` offers `saveViewState` and `restoreViewState` methods which should make this reasonably simple to implement.

**Comment by RubenRBS** [comment]
Hi! Thank you so much for your request (And the tip as to where to look in monaco, you saved me lots of time). It's a great idea! I've implemented it now for the source editor and the compiler output. 
Only thing that I'm not too sure about is the keyboard shortcut, but we can always change it at a later date if it turns out to be a bad choice.

This should be live soon :)

**Comment by Merovius** [comment]
Woohoo, that was super quick, thanks :)
