### ISSUE TITLE
[REQUEST] Improve C++ synthax highlighting

### ISSUE THREAD

**Issue by GuillaumeDua** [compiler-explorer/compiler-explorer#2866]
**Is your feature request related to a problem? Please describe.**

- The code might be difficult to read because of a lack of highlighting granularity, which is not convenient when doing live demo / teaching / trainings

**Describe the solution you'd like**

A behavior somehow similar to what Ms-VS, vs-code, or most modern IDE have to offer.

Currently, highlighting logic mostly is :

- keyword -> blue
- comment -> green
- string-literals -> orange
- everything else -> white

**Describe alternatives you've considered**

Consider adding some highlighting for :
- namespaces
- functions
- variables

**Additional context**

Perhaps stuffs like https://highlightjs.org/ might be a way to proceed ?

**Comment by mattgodbolt** [comment]
Hi! We're not a full IDE: we don't have a C++ parser, instead using MS's Monaco (which powers vs.code) for simple regex-based highlighting only. There's some discussion about adding language server support, but that would need significant resources on our server(s), and persistent connections.

The `highlightjs.org` you link has the same issues - it doesn't fully parse the text but is based off of regexes too - check the example https://highlightjs.org/static/demo/ - some simplistic guesses are made ([source](https://github.com/highlightjs/highlight.js/blob/main/src/languages/cpp.js)) but it's still "just" regexes.

**Comment by GuillaumeDua** [comment]
@mattgodbolt Yes you're right : I don't suggest to make compiler-explorer a complete IDE.

My point is that there might be a way to provide a special Javascript, client-side logic that would process code to provide a more accurate/convenient syntax highlighting. Thus which won't require any additional load on the server-side.

Perhaps I'm wrong, but I feel like https://prismjs.com/ is doing a slightly better job than highlight.js.

As a user that use compiler-explorer to teach C++, I wouldn't mind using an extra Go of ram and some CPU usage to get a more readable code while live-coding.

Ps : Consider this as a suggestion, not a request ofc.

**Comment by partouf** [comment]
Perhaps it's more productive if you could provide an example that goes wrong - in general the highlighting is as you ask.

With 1 major difference of course that namespaces, functions and variables are not coloured. This is because you only really know what they are once you understand the code, and currently, only the compiler will actually understand that. An LSP would be a way around it, but that will still involve a lot of work.

**Comment by GuillaumeDua** [comment]
@partouf 
> namespaces, functions and variables are not colored
That's precisely the point.

Once again, this a a suggestion. Compiler-explorer is an efficient tool I use on daily basis.

I understand that it requires a lot a work, but to be honest the compiler-explorers examples feel mostly like big white blocks.

Take the following code for instance :
```cpp
template <TupleInterface T>
decltype(auto) example(T && value) {
    using tuple_type = std::remove_cvref_t<decltype(value)>;
    [&value]<std::size_t ...indexes>(std::index_sequence<indexes...>){
        ((std::get<indexes>(value)), ...);
    }(std::make_index_sequence<std::tuple_size_v<tuple_type>>());
}
```
The following lines are all white, thus kinda hard to read especially when introducing new synthaxes to juniors/students :

```cpp
[&value]<std::size_t ...indexes>(std::index_sequence<indexes...>){
        ((std::get<indexes>(value)), ...);
    }(std::make_index_sequence<std::tuple_size_v<tuple_type>>());
```

**Comment by mattgodbolt** [comment]
Thanks @GuillaumeDua - we understand, but the point I think we're trying to make is that's an IDE feature. As you'll note in things like highlight.js or Github's own syntax highlighter, it's not capable of _parsing_ C++, only syntax highlighting very simple, regular-expressions.

We aren't able to parse the C++ code on the browser: there doesn't exist a general way to do this without actually compiling everything in the browser itself (including the includes etc). I'm sure you're well aware the difficulty in parsing C++ and how, without knowing what templates are instantiated etc, and without doing full name resolution, it's impossible to correctly determine what "meaning" a particular identifier has.

Thank you for the example, which is very motivating.

In order to actually perform this we would need to allocate server resources for every open web page, and run a persistent connection to something which _can_ see the whole code. This is the "Language Server Protocol" and it's what powers most IDEs, like vs.code. This is a very resource-intensive thing to do, and it's not currently feasible for us.

However; if I'm missing something, do let me know! I realise you're asking for a very reasonable feature (who doesn't like proper semantic highlighting!), and we'd love to support it but it's not as easy as one might imagine.

**Comment by GuillaumeDua** [comment]
You can close this issue/suggestion for now then.

I'll keep the idea on my side, and come back if I find a suitable, efficient way to achieve something better than what already exists.

**Comment by mattgodbolt** [comment]
Thanks for being understanding. And again: thank you for taking the time to file this and elaborate on what you want. I wish I had more time and resources to help!
