### ISSUE TITLE
[BUG] IDE mode: it's not obvious from the UI that example.ext is always present

### ISSUE THREAD

**Issue by hyphenrf** [compiler-explorer/compiler-explorer#2912]
Possible cause is optionsForFilter being insensitive to customFileName?

**Describe the bug**
BaseCompiler always compiles `example.ext` instead of `customName.ext`

**To Reproduce**
- go to godbolt.org
- open a tree view
- choose C as the language
- choose gcc as the compiler, as it doesn't override anything
- create a new source, add it and name it something like `test.c`
- add a compiler from tree view
- inspect compiler options, the file is `example.c` not `test.c`
- inspect the disassembly, `square` function is not present.. suggesting `example.c` isn't a rename, rather an entirely different file 

**Link**
https://godbolt.org/z/ET9xdaa1K

**Comment by partouf** [comment]
This is very much intended, but is also not what you think.

The UI decides what your main sourcefile is, and without cmake that's always `example.ext`. The other files like `test.c` will be placed next to that in the folder where your compilation is done. If you haven't supplied an example.ext it will be saved as an empty file.

The one thing we might be able to do is give a proper error message instead of trying to compile an empty file. It's not feasible to be flexible about filenames.

**Comment by hyphenrf** [comment]
I see.. Yeah when I added an `example.ext` implementation things worked as they should.. I'll update the issue

**Comment by partouf** [comment]
This has recently been fixed. It's not great yet because it requires a trip to the backend, but it's something.

This example now says `<File example.c has no content or file is missing>` when trying to compile the project.
