### ISSUE TITLE
[BUG] `<>` characters in unfurls get treated as HTML in some unfurls (e.g. Discord)

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2941]
e.g. https://compiler-explorer.com/z/Wxba637jr has the code:

```cpp
template<int X> int func();
```

but unfurls as:

```
Compiler Explorer - C++ (x86-64 gcc 11.2)
template int func();
```

in Discord at least.

**Comment by partouf** [comment]
I'm pretty sure we talked about this before, but I can't find the conversation. I thought it was something about < > working in some unfurlers, and if you would replace it with &lt; &gt; then it would show that instead of < > - so I think that maybe we need to get those into view and not solely look at how discord does it.

**Comment by partouf** [comment]
maybe it would be OK

![image](https://user-images.githubusercontent.com/442630/133707205-506cfca6-6d1e-463d-aa27-2b9e0ba4b0c9.png)

**Comment by RubenRBS** [comment]
Shouldn't that be happening already?
https://github.com/compiler-explorer/compiler-explorer/blob/9a1c83d34efb217dfcc11692b7249aa1fb90c648/lib/handlers/route-api.js#L176

**Comment by partouf** [comment]
addressed by https://github.com/compiler-explorer/compiler-explorer/commit/c3a72742b320888e4e38890fc02300bfa4db3c91

(background info: CloudFront sends a custom user-agent `Amazon CloudFront`. Because keeping user-agent messes with the CloudFront cache, the best decision was to get rid of user-agent branches in the code. Note that the cache for the shortlinks up until now is then pretty iffy, but we'll manage)

**Comment by partouf** [comment]
This is now live
