### ISSUE TITLE
We need TypeScript test infrastructure.

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3004]
We need TypeScript test infrastructure.

_Originally posted by @mattgodbolt in https://github.com/compiler-explorer/compiler-explorer/pull/2988#r721857601_

**Comment by supergrecko** [comment]
For context: we recently migrated ansi-to-html to TypeScript (thanks @MarkusJx) which meant the JS tests for ansi-to-html would no longer run (because what we are testing is typescript now).

Our current TS setup simply compiles to JS on the go through the webpack middleware (or statically to the CDN upon deployment). This means that our test infrastructure (which is mainly backend code) is not aware of anything related to TypeScript.

A future goal is also to migrate the backend to TypeScript, so TS test infrastructure will be necessary regardless.

Mocha (which is our test runner) has support setup for TypeScript (https://github.com/mochajs/mocha-examples/tree/master/packages/typescript) which is probably the path we want to take.

**Comment by jeremy-rifkin** [comment]
I think this is closed by #4659
