### ISSUE TITLE
[BUG] Filter library sometimes leaves orphaned instructions

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3042]
(reported on Slack)

There seems to be something funky going on with the "filter: Library Functions" feature. I ended up getting a bunch of instructions at the top with no indication of which function they are a part of https://godbolt.org/z/Pq3nW79Me

If I uncheck the "filter: Library Functions" box, it says they are part of `_ZNSt17_Function_handlerIFviEZZ14make_awaitableIiZ7my_corovEUlT_E_EDaOT0_EN7Awaiter13await_suspendENSt7__n486116coroutine_handleIvEEEUlDpOT_E_E9_M_invokeERKSt9_Any_dataOi`, which I think means that they are my lambda that got inlined into the std::function type erasure machinery (this matches what the instructions are doing).

But it seems like either the whole function (including the body) should be filtered out by that filter or not, rather than just removing the label/name but leaving the instructions.

**Comment by partouf** [comment]
GCC 11 changed a bunch of assembly annotations, I'm not happy about it. But I guess we'll have to adapt and change the parser for this :(

**Comment by Alcaro** [comment]
Just ran into this one myself. https://godbolt.org/z/1GrcjPKsx

(at least I think it's the same bug)

**Comment by partouf** [comment]
Same bug yes, library function that has references to user code

**Comment by partouf** [comment]
This is hard to change. The library filter currently filters while it's parsing the lines, in order to support inline user code, it needs to filter out library functions only later on.

**Comment by RedBeard0531** [comment]
I think there are 2 related bugs. Or perhaps a bug and a feature request. 

1. There is the bug where it currently shows instructions floating without any function name. This could be solved by filtering out the entire function if you decide to filter you the function name/label. In another sense, I think it is always a bug to partially filter a function. In this case it is noticable because the filtered part was the name, but consider how bad it would be if random instructions in the middle were silently filtered out.
2. It may be nice to see any instructions generated from "my" code even if they get inlined into a library function. But even in this case I think I would want to see the whole function (possibly with my code highlighted somehow), since a subset of a function can be misleading without context (eg it could jump to a lable that is missing).

I think 1 can be done in a line-wise, in-order parser, you would just need to skip to the end of the function if you decide to filter out the name/label. 2 is more problematic because it requires retroactively deciding to include lines that you may have already skipped. (Admittedly, I haven't actually looked at your parser, I'm just making some assumptions based on your comment and my experience working with other parsers in general)

I guess someone could see the status quo as better than having a fix for 1 but not 2, because at least you get to see your instructions. But I think showing partial functions is too much of a bug to be helpful. And if someone is interested in something that is missing, it seems reasonable for them to try turning off library filtering.

**Comment by jeremy-rifkin** [comment]
Looks similar to what's happening in clang now #5050 since llvm changed their annotations
