### ISSUE TITLE
[BUG]: Context menu lacks "paste"

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3113]
### Describe the bug

The right-click menu has cut and copy but not paste in some cases. It works on my Chrome Linux machine, but I had an email with the attached screenshot.

### Steps to reproduce

Unsure

### Expected behavior

Paste should appear.

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/633973/141993024-94c32e36-3c45-475d-9d28-5b99bfaea8c3.png)

**Comment by mattgodbolt** [comment]
From the OP:

>OS: Win10 x64
Browser: FF 74.0 (64-bit)
Please, add this on github.
Thanks!

**Comment by RubenRBS** [comment]
I don't think this is a bug. Copying and pasting is not something that browsers just let webpages do for security reasons, and most of the times, there's no way to force them from a click event.
I suspect this is the case here and it's not showing up in cases where Monaco would not be able to paste the contents of the clipboard even if it wanted, because it lacks permissions to do so

**Comment by partouf** [comment]
Firefox has the option "dom.events.asyncClipboard.readText" set to False by default, if you go to the url about:config you can change it. However that does not make Monaco decide it's suddenly allowed. Maybe because when you use readText, FF will popup a tiny contextmenu with Paste in it, which is... weird...

Got the idea via https://github.com/microsoft/monaco-editor/issues/3003

Perhaps it's possible we to make a custom paste item for the menu specifically for FF, but not sure how it will behave

**Comment by jeremy-rifkin** [comment]
Looks like 
```js
.addAction({
    id: "myPaste",
    label: "Paste",
    keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_V],
    contextMenuGroupId: "9_cutcopypaste",
    run: (editor) => {
		// actually do the paste
    }
  });
```

Will can be a solution one day (if it's not added upstream).

https://caniuse.com/mdn-api_clipboard_readtext Firefox doesn't support reading the clipboard's contents but chromium based browsers do.
