### ISSUE TITLE
[BUG]: ARM64 instruction documentation fails to display with a cryptic error

### ISSUE THREAD

**Issue by fstirlitz** [compiler-explorer/compiler-explorer#3117]
### Describe the bug

Attempting to view the documentation for an ARM64 instruction results in an unhelpful error message: ‘There was an error fetching the documentation for this opcode ([object Object]).’

### Steps to reproduce

0. Visit godbolt.org
0. Select an ARM64 compiler
0. Enter some code
0. In the assembly pane, click on a mnemonic and press Ctrl+F8.

### Expected behavior

- Documentation for the assembly instruction is displayed.
- Failing that, an informative error message is displayed.
- Failing that, the option is disabled entirely.

### Reproduction link

https://gcc.godbolt.org/z/MjnzosWdW

### Screenshots

![Screenshot of the error](https://user-images.githubusercontent.com/4331184/142170973-80ff1e0b-5c62-45f9-8bbd-f7b6ca4f334d.png)

### Browser version

Firefox ESR 78

**Comment by mattgodbolt** [comment]
How odd! I'm seeing a different issue where all the opcodes are marked as unknown (not an error).  If you feel comfortable can you open up your Firefox network tab and see what happens when you mouse over. I see a fetch of the opcode from our servers, which is served as a `200`:
![Screenshot from 2021-11-17 08-07-52](https://user-images.githubusercontent.com/633973/142215822-ab49f2fb-b7fe-4cd1-ac8f-214ba94aba9f.png)

Do you have an ad blocker that might be affecting our ability to fetch?

**Comment by mattgodbolt** [comment]
Either way: we don't currently have a source of AARCH64 documentation, so it will always return `unknown opcode`

**Comment by mattgodbolt** [comment]
AH! Sorry - ignore me!! I'm unable to read bug reports :blush:

Confirmed: hitting ctrl-F8 reproduces exactly what you're seeing!

**Comment by partouf** [comment]
this is now live

but it returns `{"error":"Unknown architecture "}` on the URL https://gcc.godbolt.org/api/asm/aarch64/msub

Should it maybe return "No documentation for architecture aarch64" ?
