### ISSUE TITLE
Integrate OSACA (if possible)

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#312]
Long requested, license issues notwithstanding, hopefully in the new UI it'll be easier to find a place for.

**Comment by mark-99** [comment]
I'd thought of this also, so clearly it is an excellent idea ;).
People tend to look at instruction count like it's perf, IACA would be much more meaningful.

**Comment by mattgodbolt** [comment]
Also requested over email recently a few times (and I've had a need for it too!)

One emailer cited https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82418 as an example

**Comment by Trass3r** [comment]
Open Source alternative:
https://github.com/RRZE-HPC/OSACA

**Comment by mattgodbolt** [comment]
Rephrasing: IACA is old, badly licensed and not supported any more. Changing this bug to track OSACA (if that's an option)

**Comment by cod3monk** [comment]
Since OSACA has recently become much more stable, we would want to know what needs to be done on our end to include OSACA support in the computer-explorer?

In the very near future (days) we plan on supporting (most) x86 instructions on Intel and AMD Zen, expand support to AMD Zen2 and ARM Neoverse N1 in the near future (weeks).

**Comment by mattgodbolt** [comment]
Hi @cod3monk ! Sorry I didn't get back to you! To add this I think taking a leaf out of `llvm-mca`'s approach (since made easier) would be advisable. We'd need a way to add a "tool" window. llvm-mca is also a whole language of its own in "analysis" mode, we could add support too.

**Comment by cod3monk** [comment]
This can be closed
