### ISSUE TITLE
[BUG]: Click the "View assembly documentation" does't pop up documentation window in chrome 96

### ISSUE THREAD

**Issue by daleydeng** [compiler-explorer/compiler-explorer#3174]
### Describe the bug

When I click the "View assembly documentation", the context menu doesn't pop up with chrome 96 in https://godbolt.org/. However in the site https://go.godbolt.org/, the documentation window can be popped up

### Steps to reproduce

1. visit https://godbolt.org with newest version of chrome browser
2. click "View assembly documentation Ctrl-F8"

### Expected behavior

The documentation window should be popped up

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Linux Fedora 35

### Browser version

Google Chrome Version 96.0.4664.93 (Official Build) (64-bit)

**Comment by partouf** [comment]
Can you give us a more complete example of this, like what compiler settings are you using and which asm-opcode are you trying to view? A link would probably be useful if possible.

**Comment by rebb** [comment]
Think i'm seeing something similar, but on Firefox.
Compiler is "x64 msvc 19.30" in this case.
Trying to view assembly documentation on any instruction ( even if it's just mov ) gives a red popup about "Error fetching documentation".

Seems that it works when switching to GCC though.

**Comment by partouf** [comment]
> Think i'm seeing something similar, but on Firefox. Compiler is "x64 msvc 19.30" in this case. Trying to view assembly documentation on any instruction ( even if it's just mov ) gives a red popup about "Error fetching documentation".
> 
> Seems that it works when switching to GCC though.

That's expected as MSVC is hosted elsewhere and doesn't have the instructionset property to determine it needs the x86 instructionset. We might be able to fix that somehow.

**Comment by jeremy-rifkin** [comment]
I think this now behaves as it should

**Comment by verhovsky** [comment]
It's still an issue and it's because of ad/tracker blocking.

With uBlock Origin enabled, when I click on this nothing happens

<img width="1279" alt="Screenshot 2024-02-16 at 11 08 53" src="https://github.com/compiler-explorer/compiler-explorer/assets/5687998/efe3e38c-c57d-4e10-8986-14f7fee4fca5">

and there's no new errors in the JavaScript console after the click, just the old `POST https://sentry.io/api/102028/envelope/?[...] net::ERR_BLOCKED_BY_CLIENT` errors because of the ad blocker.

Using uBlock Origin 1.55.0 on Chrome 121.0.6167.184 on macOS 14.3.1
