### ISSUE TITLE
[BUG]: unicode handling maybe broken

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3288]
### Describe the bug

In a tweet someone posted https://godbolt.org/z/fdWx983sa which tries to `std::wcout` some unicode things.

### Steps to reproduce

Click the link and see the output is `SomeText F F`

### Expected behavior

The output should contain unicode chars, something like `SomeText Φ Φ"`

### Reproduction link

https://godbolt.org/z/fdWx983sa

### Screenshots

Not applicable

**Comment by partouf** [comment]
It works if you use the regular cout https://godbolt.org/z/PrWz39Mcb

**Comment by partouf** [comment]
it also works for wstring if you do a setlocale
https://godbolt.org/z/68o6fjvdo

Trying to rack my brain on why this exactly is, because it should still be outputting in the linux default locale (which I thought was actually utf8, but maybe I'm wrong) on both cout and wcout?

Not sure what the mechanisms behind wcout are in this case.

**Comment by partouf** [comment]
The default set locale on our instances is utf8, so the setlocale shouldn't really be doing much in theory, but apparently it does

```
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

**Comment by partouf** [comment]
AH, if I change the locale to C.UTF-8, it display's F instead of the correct character. So maybe this is a language dependent utf8 encoded character?

**Comment by partouf** [comment]
So this also works: https://godbolt.org/z/n9MToz34K

So maybe wcout just is just bugged when setlocale is not called?

**Comment by partouf** [comment]
Note Clang libc++ doesn't know how to deal with wstring/wcout at all, and icc needs setlocale as well

**Comment by partouf** [comment]
So basically this is just a C++ thing, not a CE bug afaik

**Comment by deanturpin** [comment]
`fmt::print` also starts working with the addition of `setlocale`.

```c++
int main() {

  setlocale(LC_ALL, "en_US.utf8");

  const auto out = std::wstring{L"cya \u03A6"};
  fmt::print(L"{}\n", out);
}
```
https://godbolt.org/z/xKWjTs6z7

**Comment by partouf** [comment]
Dug a bit into cppreference and the GCC testsuite, and they basically do this too when testing `std::wcout` with unicode characters
```
    std::locale loc("en_US.UTF-8");
    std::locale::global(loc);
```

e.g. https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/libstdc%2B%2B-v3/testsuite/27_io/objects/wchar_t/11.cc

They only seem to not use it in situations with just ASCII.

There's also examples on the internet calling `std::imbue(std::wcout, loc)`, but that only applies to language related formatting as far as I can tell. The `global()` call also affects the encoding/decoding.

It might be that it's a GCC bug that they haven't noticed because it's never tested without `global()` - but that's just speculation from my perspective. I don't know what the standard says on this subject, but I bet it's one of those "implementation defined" kind of things.

**Comment by jeremy-rifkin** [comment]
Resolved now

**Comment by Alcaro** [comment]
you sure? The reproduction link still prints SomeText F F, not the expected SomeText Φ Φ.

If you want to close as "not our problem", that's fine, but closing as resolved when it isn't feels kinda strange to me.

**Comment by partouf** [comment]
> you sure? The reproduction link still prints SomeText F F, not the expected SomeText Φ Φ.
> 
> If you want to close as "not our problem", that's fine, but closing as resolved when it isn't feels kinda strange to me.

That was what Jeremy meant but worded it inprecisely, it's OS+Compiler implementation defined if you use wchar functions and usually requires `setlocale` to be used correctly (see example given for https://en.cppreference.com/w/c/io/fputws). It is assumed you would use `setlocale`, otherwise all you're guaranteed on is the first 0-127 chars (if not just a-zA-Z0-9).

**Comment by jeremy-rifkin** [comment]
Correct, closed as it sounds like it's not a CE issue
