### ISSUE TITLE
[BUG]: Ada and IDE mode not working

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/compiler-explorer#3459]
### Describe the bug

Can't really understand how IDE mode is supposed to work with Ada.

### Steps to reproduce

1. Create 2 files `example.adb` and `example.ads`
2. doesn't build with:
 ```
<source>:1:14: file "example.ads" not found
```

### Expected behavior

Correct build :)

### Reproduction link

https://ada.godbolt.org/z/x5xK1Tcfr

### Screenshots

Not applicable

**Comment by partouf** [comment]
> oh, ok, thanks. Wasn't really clear to me. Now, there's still the hardcoded `example` in `ada.js` that gets in the way and forces the main file to be called `example.adb`.

Right. The question then is how the compiler is supposed to know what to call it. When we use CMake with C++, you can enter a custom executable name, but you can't in the regular IDE mode because we'd have to rewrite and retest a bunch of stuff to accept and use the custom executable name. In CMake mode this was easier because it was a new API call...

**Comment by jhkhouri62** [comment]
I teach computer science and I am using godbolt to share codes in different languages. In the last semester all ADA code was running fine. I was checking the material for this semester and I noticed that ADA code is not running. It shows the following message:
_try "gnatmake --help" for more information.
Compiler did not produce an executable_

Link: https://ada.godbolt.org/z/8EPEsEsr3

I am trying the Three version, but still not working.

Any help?
Thanks.

**Comment by dkm** [comment]
I'll have a look. It's the execution and compile to binary parts that are broken

**Comment by partouf** [comment]
PR was merged, we can close this issue
