### ISSUE TITLE
[BUG]: `/app` is stripped from the beginning of program output

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3626]
### Describe the bug

Any program output is subject to the same filtering we do for compiler output; stripping the leading `/app/` from filenames. This is confusing

### Steps to reproduce

1. click the link and observe the output

### Expected behavior

We should see the full output, and instead only see `foo` (not `/app/foo`)

### Reproduction link

https://godbolt.org/z/jo49E58Kz

### Screenshots

Not applicable

**Comment by partouf** [comment]
I'm sure we had an issue about this before, but I can't really find it anymore.

The problem is mostly the function that we use for highlighting asm and errors is the same function. So I guess to sort-of fix this is to remove the special filename parsing when running a user built executable. Here -> https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/base-compiler.js#L360

**Comment by partouf** [comment]
also https://github.com/compiler-explorer/compiler-explorer/issues/3046

**Comment by OfekShilon** [comment]
Seems fixed
