### ISSUE TITLE
[BUG]: "Full compiler version" popover does not display the correct version

### ISSUE THREAD

**Issue by igor-makarov** [compiler-explorer/compiler-explorer#3858]
### Describe the bug

When viewing the "Full compiler version" popover in the main UI, the version information does not match the actual compiler version. This occurs in 'nightly' compiler versions where the full version changes a lot.

From a brief discussion with @partouf this is because the popover info is only updated when the site gets deployed. Many days could pass between deployments, causing the info to be out of sync the entire time. 

This leads to confusion and possibly wasted time. 

If it's too complex to retrieve this version info dynamically into the popover, perhaps the popover can be removed? The info is accessible through the command-line flags and this would improve correctness.

Thank you!

### Steps to reproduce

1. Open `swift.godbolt.org`.
2. Select a nightly compiler.
3. Add `-v` to compiler options.
4. Observe the version in the output and the version in the popover.

### Expected behavior

The versions should match.

### Reproduction link

https://swift.godbolt.org/

### Screenshots

<img width="745" alt="Screen Shot 2022-07-09 at 15 31 52" src="https://user-images.githubusercontent.com/16595309/178106004-dc819233-05ed-4193-85e1-c679d780980e.png">

### Operating System

Not applicable

### Browser version

Not applicable

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to create the issue, we really appreciate it.

Just as a bit of insight into why this occurs: 
This issue comes from our way to speed up instance startup times. We currently host 1372 (`curl -s https://godbolt.org/api/compilers | wc -l` - 1) compilers. As you might imagine, calling `--version` on all of them would make the startup of each instance take ages, which is not too good. Our solution is to call them once on a compiler discovery build step and cache the responses as a build artifact.
So with that in place, even though we change the nightly compilers executables every day, we do not rerun the dicovery until a new build is triggered and pushed live, nor do we run the version commands on those compilers - So the cached values still mention the now outdated responses.

So, all in all, there's not much we can do to keep this info updated without lots of changes to the current system. The good news is that we've been talking about ways to improve our builds, and some of the paths have us dropping the discovery phase, which would potentially allow to keep the versions of nightly compilers up-to-date

**Comment by RubenRBS** [comment]
One trick we can do for this case is to have some info text in the popout for nightly compilers that says something like
> This version info might be outdated by up to X days

**Comment by igor-makarov** [comment]
@RubenRBS Wht do you think of my earlier suggestion of removing the version info?

Perhaps for nightlies, the popover can say "Nightly version, to see build number use compiler command line options" and not show the version that can be outdated?

**Comment by RubenRBS** [comment]
Yes, you're probably right, the better option would be to hide the info if we know it's outdated. The only roadblock now is that the site doesn't actually know which compilers get built nightly and should get the warning text displayed, so that's the first thing we should take a look into. Thanks for your feedback :)

**Comment by partouf** [comment]
One other thing we've been thinking of was to refresh the discovery nightly after installation (for the current version), but that would still not be a guarantee to the new version info showing up, because then it would depend on the cycling of instances. Unless we would actually refresh the instances, but I'd really not like to do that automatically in case things go wrong.

**Comment by igor-makarov** [comment]
Is there a CDN somewhere in the project? If there is, we could set up version metadata caching with eTags and it could be updated on demand only when the compiler itself changes.

**Comment by partouf** [comment]
> Is there a CDN somewhere in the project? If there is, we could set up version metadata caching with eTags and it could be updated on demand only when the compiler itself changes.

There is, sure. Still is a lot of work that we have to do. So question is what's really the best way.

**Comment by igor-makarov** [comment]
Ok, I ran the server locally and I've noticed some odd behavior:
 * There's a `rescanCompilerSecs` prop which appears to be set to 1 hour for Amazon.
 * There's a `--prediscovered` option that accepts a JSON (I'm guessing this is the file from the build step).
 * When the `--prediscovered` option is specified, the rescan doesn't occur.

The last one got changed in #3040 and I think that if it were re-enabled, then the compiler reload would proceed correctly and efficiently. There's mtime-based caching in place to avoid calling the `--version` unnecessarily. 

My question then becomes, what was the root cause for #3040 and can it be resolved without turning off the rescan?

Testing locally, I did not encounter any problem rescanning after loading prediscovery. Was there some issue that went away in subsequent changes?

**Comment by partouf** [comment]
It might cause issues, but it would be that those were solved by some other change. The main issue is a different one, namely that it might cause the remote MSVC compilers to suddenly disappear.

**Comment by igor-makarov** [comment]
Why does it cause them to disappear? Is it because rescan only discovers local ones?

We could make sure that the rescan is additive - that it won't remove existing compilers but only add/modify.

**Comment by partouf** [comment]
Sorry I didn't clarify.
The point is that the MSVC servers are quite unstable at times, but they still usually work again after a couple of tries. But when the rescan happens and they're unavailable for 1 instance, that instance gets out of sync with our other instances. This causes issues because 1 user will have MSVC compilers missing, and other users won't. We'd rather have them visible for everyone always even if they're temporarily not available.
The rescan is really not a solution.

**Comment by igor-makarov** [comment]
Ohhh. @partouf thanks for clarifying. I think this can be resolved by making the compiler rescan non-removing:
1. Scan for new compilers
2. If compiler is in both lists, replace with newer
3. if compiler is *only* in the new list, add it
4. If compiler is *only* in the old list, leave it there
