### ISSUE TITLE
[BUG]: ld: cannot find -lgtestd and -lgmockd

### ISSUE THREAD

**Issue by dornbirndevelops** [compiler-explorer/compiler-explorer#3889]
### Describe the bug

linking fails for Google Test libraries on Clang and Gcc (tested on latest version each)
did the linking targets get a renaming?

### Steps to reproduce

1. see example [here](https://godbolt.org/z/3Ye18Tdzv)

### Expected behavior

Dependencies to Google Test should be properly linked --> example above should work as it did in the past.

### Reproduction link

https://godbolt.org/z/3Ye18Tdzv

### Screenshots

![image](https://user-images.githubusercontent.com/25949821/179910804-669da542-462b-4b0c-ae59-ee30736a6553.png)

**Comment by partouf** [comment]
There's a couple of things going wrong;
* They seem to have removed the d suffix for the debug build of the library
* For Clang trunk it seems that this stopped compiling because it can't find the right libc nor the right library path for libstdc++ (also for the libc++ version)

I did recently change the Ubuntu version for the library builder, I might need to install extra libc versions somehow. That might solve the Clang trunk issue.

The missing d suffix will require a change to the properties files for gtest trunk.

**Comment by jacobsa** [comment]
FYI this issue is causing trouble for me too. Thanks for filing.

**Comment by partouf** [comment]
I have just pushed the last few fixes live, this should be fixed now. Let me know when a certain compiler/library combination is not working.

**Comment by jacobsa** [comment]
Excellent, thanks!

**Comment by tilir** [comment]
Seems to happen again. Filed https://github.com/compiler-explorer/compiler-explorer/issues/4046

**Comment by tilir** [comment]
@partouf FYI
