### ISSUE TITLE
[BUG]: Unable to execute programs using wine-vc

### ISSUE THREAD

**Issue by edmcman** [compiler-explorer/compiler-explorer#3985]
### Describe the bug

I am trying to execute programs compiled with wine-vc.  I get the following error:

```
Could not execute the program
Compiler returned: -1
Compiler stderr
<spawn /usr/bin/wine ENOENT>
```

I enabled debug output, and this is probably from a cwd that doesn't exist: `"cwd":"mp/compiler-explorer-compiler2022723-53-1dkihet.ihfx"`

I assume this is caused by this: https://sourcegraph.com/github.com/compiler-explorer/compiler-explorer/-/blob/lib/compilers/wine-vc.js?L54

So, uh, what is that line of code there for?  Am I doing something wrong?

### Steps to reproduce

I am trying to build a docker container with compiler-explorer and MSVC.  The easiest way to reproduce is to use that:

https://github.com/edmcman/docker-msvc-compiler-explorer

Then try to execute any C++ program using Visual C++ 2005 or 2008.

### Expected behavior

The program executes

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/1017189/186422207-ba320a1e-918d-41a2-84d4-a120589b3511.png)

**Comment by partouf** [comment]
Wine execution of has never really been tested because we don't have the runtime SDK installed for MSVC on our linux machines.

This line is to remove the "Z:" in front of the path, but it assumes (perhaps too much) the `filename()` is called for the inputFilename before this gets run. I suspect adding a check for `if (inputFilename.startsWith('Z:'))` and only then do the `substr`, would fix it.

It may be that it should actually be fixed in https://github.com/compiler-explorer/compiler-explorer/blob/46cdf8f4a504e68591d1695eedc3ddfb791c88e5/lib/base-compiler.ts#L1374 as that doesn't call filename() - but that has other consequences as well. Or perhaps an override of https://github.com/compiler-explorer/compiler-explorer/blob/46cdf8f4a504e68591d1695eedc3ddfb791c88e5/lib/base-compiler.ts#L1277

I can't really say for sure.

If the if startswith Z works, thats the safest way out. If not it will need some more thought.

**Comment by edmcman** [comment]
I suppose I have a stupid question.  Why would Z: be in the path at all?  If we're running wine, then presumably we're on Linux, and that filename would be in a UNIX temporary directory.

Is it possible this line was copied from WSL or Windows code?

**Comment by partouf** [comment]
> I suppose I have a stupid question. Why would Z: be in the path at all? If we're running wine, then presumably we're on Linux, and that filename would be in a UNIX temporary directory.
> 
> Is it possible this line was copied from WSL or Windows code?

No, it's old code. Z: is there because inside wine that's the disk where you have full access to /. It was initially setup in a way that we thought the diskletters were important.

**Comment by edmcman** [comment]
Ok, that makes sense.  I guess the better question is can that path actually ever start with Z: at this point?

Based on my limited reading of the source code, I don't think it can, because that path will ultimately come from https://sourcegraph.com/github.com/compiler-explorer/compiler-explorer/-/blob/lib/base-compiler.ts?L266:5&subtree=true

**Comment by partouf** [comment]
> Ok, that makes sense. I guess the better question is can that path actually ever start with Z: at this point?
> 
> Based on my limited reading of the source code, I don't think it can, because that path will ultimately come from https://sourcegraph.com/github.com/compiler-explorer/compiler-explorer/-/blob/lib/base-compiler.ts?L266:5&subtree=true

filename() is always called "last minute" just before it's passed to for example runCompiler() and similar functions where the inputfilename is a parameter to a compiler, https://github.com/compiler-explorer/compiler-explorer/blob/46cdf8f4a504e68591d1695eedc3ddfb791c88e5/lib/base-compiler.ts#L1591

**Comment by edmcman** [comment]
Ok, I'll work on a PR to test for "Z:" and only use the substr if it is present.  I believe that should fix my situation.

**Comment by edmcman** [comment]
PR in #3986

Execution is working perfectly with those two commits!
