### ISSUE TITLE
[BUG]: "LLVM IR" view fails for rust with "Compile to binary" on

### ISSUE THREAD

**Issue by SamB** [compiler-explorer/compiler-explorer#4054]
### Describe the bug

The LLVM IR view isn't working for Rust, but this doesn't look exactly the same as https://github.com/compiler-explorer/compiler-explorer/issues/2165 and it seems to happen for all versions of rust that I try.

### Steps to reproduce

1. Visit godbolt.org
2. Select Rust and some version of `rustc`
3. Put something with a `main` into the input box, e.g.:

    ```rust
    // Type your code here, or load an example.
    pub fn square(num: i32) -> i32 {
    num * num
    }
    
    // If you use `main()`, declare it as `pub` to see it in the output:
    pub fn main() {
    }
    ```

4. Turn on "Output > Compile to binary"
6. Click "Add New > LLVM IR"

### Expected behavior

The LLVM IR should be there, or at least a reasonable explanation of why not.

### Reproduction link

https://godbolt.org/z/c7xr4Pjq5

### Screenshots

As you can see, it just prints this instead:
```
Internal error; unable to open output path
```
![image](https://user-images.githubusercontent.com/13903/189743794-b5941611-9039-486d-9238-6a090a03ef18.png)

**Comment by RubenRBS** [comment]
Hi! Sorry for the radio silence, it's been a busy month and this fell thru the cracks. I'm taking a look now, but in the meanwhile, thanks for taking the time to file the issue :)

**Comment by RubenRBS** [comment]
The issue is that we expected rustc to always output the llvm-ir in a `output.ll`, as we normally call it with `--emit asm --emit llmv-ir`, which makes it output:
```
warning: due to multiple output types requested, the explicitly specified output file name will be adapted for each output type

warning: 1 warning emitted```
and then creates both .s and .ll files.

In the binary case, we only ask it to emit llvm-ir, so it interprets that the passed `-o output.s` is for the llvm-ir. In hindsight it makes some sense, but this flew under our radar until now

**Comment by RubenRBS** [comment]
The issue is that we expected rustc to always output the llvm-ir in a `output.ll`, as we normally call it with `-o output.s --emit asm --emit llmv-ir`, which makes it warn us with:
```
warning: due to multiple output types requested, the explicitly specified output file name will be adapted for each output type

warning: 1 warning emitted
```

and then rustc goes ahead and creates both the `output.s` and `output.ll` files.

In the binary case, we only ask it to emit llvm-ir, so it interprets that the passed `-o output.s` is for the llvm-ir. In hindsight it makes some sense, but this flew under our radar until now
