### ISSUE TITLE
Improve TS `any` types in `static/panes/pane.ts`

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/compiler-explorer#4365]
We define the types for the callbacks in `static/events-map.ts` and the ones that are used in the base `Pane` class have most parameters typed as `any` or `unknown` (Such as `Pane::onCompileResult`). Would be great to have those match the ones defined in the `events-map` file

**Comment by ArtAhmetaj** [comment]
Would like to work on this, do you mean that types should be defined for all callback functions in events-map and referenced there and also on the Pane methods?

**Comment by RubenRBS** [comment]
Hi! Thanks, we really appreciate you taking the time to do this!

Yes my description could be a bit hard to understand, sorry.
Right now we define event callbacks in the events-map file, and most of them have proper typings. 

The issue is that the Pane class that then implements those callbacks uses `any` for their parameters, when they are better specified in the events-map file than just the simple `any`.

With "implements", I mean that the class calls to `this.eventHub.on(<eventName>, <this.functionCallback>);` and then `this.functionCallback` is executed whenever the event fires.

The issue might also be present in the rest of the panes in the `static/panes/` folder, so feel free to look at those too.


If you have any other question or problem, we're super glad to help, just let us know :)

**Comment by ArtAhmetaj** [comment]
Hi Ruben!
I understood all you meant by your explanation, thank for elaborating!

I have done changes on the pane file but as I see this is only an abstract class which most files on the static/pane folder override.

Mostly the issues are with compiler either being any or unknown coupled with the result and I have fixed that on the main file, 
the issue with the other files is that they mostly abuse the any type to enter whichever type needed on the onCompiler and onCompilerResult overrides.

I have attached an image to showcase what I mean:

![image](https://user-images.githubusercontent.com/48222756/205112372-aa971523-8ee0-4d53-a620-8e808ded82fd.png)

My idea here is just to add new properties to the CompilationInfo type, and extend this PR, just wanted to explain first since this is my first contribution. If you have a better idea here let me know!

**Comment by RubenRBS** [comment]
> My idea here is just to add new properties to the CompilationInfo type, and extend this PR, just wanted to explain first since this is my first contribution

Yes! This is the right solution here. The TS conversion process has been challenging and some types are still lacking their proper values (You can check that we do in fact return `supportAstView` and others like it in your browser's Network tab) so feel free to fill-in as many as needed.

And again, thanks for taking the time to contribute to CE!
