### ISSUE TITLE
[BUG]: Flash of black when reloading site

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#4535]
### Describe the bug

See title and screenshots

### Steps to reproduce

1. Set browser preference to white theme
2. Open site

This bug started appearing around 2022-12-26. I reported it to Discord, but I think it got lost.

### Expected behavior

Stay on white theme the entire time

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/5085186/210615414-b8d85ae7-6876-41a4-bebf-53cc2537990e.png)

The empty sponsors box, lack of anything below it, are intentional; they didn't load yet.

After a few seconds, it turns into the correct

![image](https://user-images.githubusercontent.com/5085186/210615536-576f604e-7246-44de-b86e-763f4970717e.png)

(ignore the squished sponsor box, I resized the browser; no point making the screenshots too wide)

**Comment by RubenRBS** [comment]
Thanks for moving the report to GitHub, it did indeed get lost between all the Discord messages :/

The issue is that we currently guess that the theme is dark early on in the process to avoid a flash of white for people using the dark theme, which is subjectevly more annoying that the current alternstive.

The fix for this would be not to guess and actually look at the theme, which I think should be doable, but I'll let you know when I try to fix it :)

**Comment by KaKi87** [comment]
Hello,

The opposite problem also exists : when using the dark theme, the page remains white for several seconds on reload.

Thanks

**Comment by Alcaro** [comment]
Seems to have been fixed sometime during the last year.
