### ISSUE TITLE
[BUG]: wasm-clang doesn't have any stdlib

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#4901]
### Describe the bug

There's no STL available for wasm-clang

### Steps to reproduce

Visit the link and see there's no `<anything>` headers

### Expected behavior

Headers should be available.

### Reproduction link

https://godbolt.org/z/KrafKv9xq

### Screenshots

Not applicable

**Comment by partouf** [comment]
Unless you have some new information on this. Afaik even libc++ is not compatible with wasm, because even things like the string library depend on cstdio, and cstdio depends on system IO, which is not available in wasm by default.

You'll need something [wasi-sdk](https://github.com/WebAssembly/wasi-sdk), [wasi-libc](https://github.com/WebAssembly/wasi-libc) and/or [emscripten](https://emscripten.org/).

Or have someone write a custom standard library like https://github.com/web-dom/stdwasm

There have been talks about this
https://www.youtube.com/watch?v=5N4b-rU-OAA 
https://www.youtube.com/watch?v=5dcqJF0pZk0

So as far as I'm aware. This is working as intended.

**Comment by mattgodbolt** [comment]
Thanks Partouf! That seems about right!
