### ISSUE TITLE
[BUG]: editor hides languages in drop-down list

### ISSUE THREAD

**Issue by mmozeiko** [compiler-explorer/compiler-explorer#4988]
### Describe the bug

Editor on https://godbolt.org/ does not show more than 50 languages in drop-down list. Last language is Solidity, but there are 5 more hidden - Swifth, TypeScript Native, Vala, Visual Basic, Zig. You can get access to these languages only by search. 

### Steps to reproduce

1. Go to https://godbolt.org/
2. Notice language drop-down has only 50 elements.
3. Open JS console and enter `$("#tomselect-1").tomselect.settings.maxOptions=null;`
4. Notice now drop-down now has all 55 elements.

### Expected behavior

Language drop-down should show all languages. Just like [compiler version drop-down](https://github.com/compiler-explorer/compiler-explorer/blob/main/static/widgets/compiler-picker.ts#L120) allows to choose all compiler versions.

This can be done by setting `maxOptions` value of TomSelect to `null`: https://tom-select.js.org/docs/#maxoptions
It should be added here: 
https://github.com/compiler-explorer/compiler-explorer/blob/main/static/panes/editor.ts#L563-L579

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment]
Confirmed, thank you for noticing and triaging. Looks like we set maxOptions for the compiler picker
https://github.com/compiler-explorer/compiler-explorer/blob/d72d2d8c0fa93fd3a71ca985ac9fa028627d02d2/static/widgets/compiler-picker.ts#L120

If you'd like to make a PR we'll happily merge it, otherwise one of us can make one later!
