### ISSUE TITLE
[BUG]:  same input, different results on godbolt.org

### ISSUE THREAD

**Issue by herrmanthegerman** [compiler-explorer/compiler-explorer#5022]
### Describe the bug

I ran a small test program on [godbolt.org](https://www.godbolt.org) and depending on the UI layout configuration get different results although the compiler configuration is the same (clang 16.0.0)  as are the compiler options.

First layout is the default configuration where one pane is called "Executor" and there's no assembler output available:

https://godbolt.org/z/Phh1vd8a5

Second layout is with assembler output and compiler output in two different window panes:

https://godbolt.org/z/PEbzETPo4

### Steps to reproduce

Open the first link. The program outputs "hello". The diagnostic output is "Killed - processing time exceeded"

Open the second link. The program outputs "hello" twice. The diagnostic output is "Program returned: 139"

### Expected behavior

Both window pane configurations should yield the same results (output and return code wise).

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Windows 10

**Comment by RubenRBS** [comment]
Hi!
Thanks for your report. The issue here is that you are not passing the arguments for the compiler to the executor pane, but to the compiled program.
The output is different because by passing `-O3` in the compiler version the infinite loop is removed by the compiler, but for the executor no such flag is pased and the process gets killed after a bit when it gets stuck in the infinite loop.

Note how https://godbolt.org/z/9qf1Gz3Gx is similar to your executor example but the compiler input has been moved to the top text bar, the one corresponding to the compiler options.

I recommend toggling off the "Arguments" input button so the input text does not show up when unecessary as to avoid confusions like this :)

**Comment by jeremy-rifkin** [comment]
I'll go ahead and close
