### ISSUE TITLE
[BUG]: Renaming source from its pane in IDE mode does not update the entry in the tree pane

### ISSUE THREAD

**Issue by ckardaris** [compiler-explorer/compiler-explorer#5734]
### Describe the bug

When renaming a file from its source editor pane while in IDE mode, the entry of the file in the `Tree` pane is not updated accordingly.

### Steps to reproduce

1. Visit godbolt.org
2. Select the `C++ Cmake template`
3. Add new source editor from anywhere in the interface (tree view, top bar, compiler view, etc.)
   - See that the a file named `C++ source #x` is added in the excluded files of the `Tree` pane.
4. Go to the newly opened source editor pane
5. Click the rename button on the top of the tab and rename to something like `test.cpp`.

### Expected behavior

The entry in the `Tree` pane should also be updated  accordingly.

Note:
Renaming from the rename button of the entry in the `Tree` pane works as expected and renames also the linked source editor pane, but only if the source editor name has not been changed before with the above buggy steps.

### Reproduction link

Not applicable because reloading with the link will make sure that opened source editor panes have correct names. In that case the name shown in the `Tree` pane is kept.

### Screenshots

On the screenshot you can see I have renamed the file, but the entry is not updated.
![image](https://github.com/compiler-explorer/compiler-explorer/assets/13348142/cd1d54ca-5c59-40a1-8d12-96e4c8537d59)

**Comment by partouf** [comment]
The pane name editing never really worked and it was never really meant as a filename, so I didn't take them into consideration when coding IDE mode.

I think we talked about maybe removing the option altogether because it's really buggy anyway, but I can see the appeal in changing the filename from there when in IDE mode because it saves an extra step of looking up the name in the tree.

Not sure how easy to implement, but should be doable I think.
