### ISSUE TITLE
[BUG]: Julia assembly is missing imported functions

### ISSUE THREAD

**Issue by Uroc327** [compiler-explorer/compiler-explorer#5752]
### Describe the bug

Julia code which `import`s functions from `Base` to add methods is not shown in the assembly output.

### Steps to reproduce

```julia
import Base: iterate, iterate, IteratorSize, IteratorEltype, eltype, length, isdone

function cilog2(i::Integer)
	ret = 8 * sizeof(i) - 1
	max = one(i) << ret

	while !iszero(max)
		iszero(i & max) || break

		max >>>= 1
		ret -= 1
	end

	ret + 1
end

# LSB first
struct IterOnes{T<:Integer}
	x::T
	IterOnes(x::T) where {T<:Integer} = new{T}(x)
end

struct IterOneState{T<:Integer}
	x::T
	i::T
end

iterate(iter::IterOnes{T}) where {T} = iterate(iter, IterOneState{T}(iter.x, 1))

function iterate(iter::IterOnes{T}, state) where {T}
	Base.isdone(iter, state) && return nothing

	@show s = IterOneState{T}(state.x >>> 1, state.i + 1)

	iszero(state.x & 0x1) && return iterate(iter, s)

	return (state.i, s)
end

Base.IteratorSize(  ::Type{<:IterOnes}) = Base.HasLength()
Base.IteratorEltype(::Type{<:IterOnes}) = Base.HasEltype()

eltype(::Type{<:IterOnes}) = Int
length(iter::IterOnes) = count_ones(iter.x)
Base.isdone(iter::IterOnes) = iszero(length(iter))
Base.isdone(iter::IterOnes, state::IterOneState) = state.i > cilog2(iter.x)

precompile(iterate, (IterOnes{Int}, IterOneState{Int}))
iterate(IterOnes(10))
```

### Expected behavior

The assembly output should include code for `iterate(::IterOnes{Int64}, ::IterOneState{Int64})` but doesn't.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by OfekShilon** [comment]
Repro link: https://godbolt.org/z/7c9E9axY9

Note the 'Library functions' filter is disabled for Julia:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/73080/2c66a69f-458e-435a-b552-1ec7d71bb660)

this is because `julia.default.properties` doesn't include `supportsLibraryCodeFilter=true`, but even adding it doesn't change anything.

@Uroc327 can you please explain how exactly did you get an assembly dump containing `iterate`?  (perhaps by disassembling a complete executable?)

@aw32   FYI.

**Comment by aw32** [comment]
The Julia wrapper would not find methods that are defined in the input code, but whose function is declared in an imported module (e.g. Base).
Now this should be fixed.
I also found and fixed a bug with parametric methods.
Note: The `Library functions filter` option has no effect, since the feature is not implemented in the Julia wrapper code and it is not well integrated with the rest of the compiler-explorer tools.

The output will now include the following methods:
```
<cilog2 Int64>
<isdone Main.Godbolt.IterOnes{Int64}, Main.Godbolt.IterOneState{Int64}>
<iterate Main.Godbolt.IterOnes{Int64}>
<iterate Main.Godbolt.IterOnes{Int64}, Main.Godbolt.IterOneState{Int64}>
```

@Uroc327 Thanks for finding and reporting this bug.
@OfekShilon Thanks for notification.
