### ISSUE TITLE
[COMPILER REQUEST]: PyPy Python runtime

### ISSUE THREAD

**Issue by jtmoon79** [compiler-explorer/compiler-explorer#5761]
### Compiler name

PyPy

### Compiler version

PyPy3.10, PyPy3.9

### Compiler language

Python

### Compiler homepage

https://www.pypy.org/

### Motivation

PyPy's claim to fame is it [significantly faster than CPython](https://www.pypy.org/features.html#speed) (the official Python runtime).  I would like to understand this in-depth by comparing Python code snippets compile by PyPy versus those compiled by CPython.

PyPy has been a well-known Python project for at least a decade now.  And it seems to be continue chugging on, implementing new Python versions slowly but surely. PyPy follows the official Python versions and features (2.7, 3.9, 3.10, etc.) but does it's own implementation of each.
It would be cool if I could use compiler-explorer to investigate differences.

**Comment by narpfel** [comment]
See #5992.

However, PyPy’s bytecode is essentially the same as CPython’s, and the speedup is mostly a result of PyPy’s JIT in combination with its memory management strategy (it uses tracing garbage collection instead of reference counting), so Compiler Explorer might not be ideal to visualise this.
