### ISSUE TITLE
[BUG]: Functions may not appear in output when using rust >= v1.75.0

### ISSUE THREAD

**Issue by sadlerap** [compiler-explorer/compiler-explorer#5939]
### Describe the bug

Assembly output filtering appears to be overfiltering some functions from Rust's compiler output for rust versions >= v1.75.0.  Appears to also happen with nightly versions.

### Steps to reproduce

1. Visit godbolt.org
2. Change language in source pane to Rust (the default source listing is enough)
3. Enable optimization flags (`-O` is enough to reproduce)
4. View output pane

### Expected behavior

The assembly output of the default function should be there.

### Reproduction link

https://godbolt.org/z/s8nnqv377

### Screenshots

Not applicable

**Comment by partouf** [comment]
The issue and possible solutions are discussed here https://github.com/compiler-explorer/compiler-explorer/issues/5782
This is really just due to how the compiler behaves.

But as far as CE is concerned, we have no plans changing the behavior unless someone sends a PR that can address this, for example a new default sourcecode so people know how to circumvent the issue.

For example adding `#[inline(never)]` with a description of it

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/issues/119850 tracks this issue on the Rust side.
