### ISSUE TITLE
[BUG]: Local Zig installation fails to compile, compiler fails with unrecognized parameter: '--output'

### ISSUE THREAD

**Issue by Validark** [compiler-explorer/compiler-explorer#6070]
### Describe the bug

Unfortunately, upon installing and opening `http://localhost:10240/`, the Zig compiler just fails with `unrecognized parameter: '--output'`. So presumably, compiler explorer is passing the parameters into Zig incorrectly by default.

### Steps to reproduce

I ran the following commands:
```
git clone https://github.com/compiler-explorer/compiler-explorer.git --depth 1
cd compiler-explorer
make EXTRA_ARGS='--language zig'
```

For the sake of completeness, here are the versions I am working with:

| cmd| version|
|:-:|:-:|
| zig | 0.12.0-dev.2236+32e88251e |
| node |  v20.9.0 |
| npm | 10.1.0 |

### Expected behavior

the compiler should pass the arguments into Zig in the right way

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Pop!_OS 22.04 LTS (Based on Ubuntu)

**Comment by partouf** [comment]
you will need to set the `.semver` property like we do here https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/config/zig.amazon.properties#L40 otherwise CE will assume you're running an older version that used `--output` (https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/compilers/zig.ts#L133)

**Comment by Validark** [comment]
Thanks for the tip! Could we make CE grab the zig version automatically using `zig version`?
