### ISSUE TITLE
[BUG]: Support for std::stacktrace (for C++) is broken

### ISSUE THREAD

**Issue by eyalroz** [compiler-explorer/compiler-explorer#6103]
### Describe the bug

GodBolt C++ compilers refuse to recognize std::stacktrace, so you can't use it.

### Steps to reproduce

1. Visit: Godbolt
2. Try to compile the following code with C++23, and either gcc 13.2 or clang 17

```
#include <iostream>
#include <stacktrace>

int main() {
    std::cout << std::stacktrace::current() << '\n';
}
```

### Expected behavior

Program should compile and run

### Reproduction link

https://godbolt.org/z/4YdecWcce

### Screenshots

Not applicable

**Comment by partouf** [comment]
This seems to have broken from gcc 13, still works in 12.3

**Comment by partouf** [comment]
For GCC 13 the define `_GLIBCXX_HAVE_STACKTRACE` is not configured and `stdc++_libbacktrace.a` is missing.

I think we need to rebuild our GCC 13's @mattgodbolt @dkm 

GCC trunk does work (with `-llibstdc++exp`)

(I think this is probably a bug in the build for v13 and we have to manually pass something)

**Comment by dkm** [comment]
https://github.com/compiler-explorer/gcc-builder/blob/a56a428ade2f6bd14841a95bb3a4a6d95fc0a61f/build/build.sh#L98
We are only doing this for trunk because of https://github.com/compiler-explorer/gcc-builder/commit/79b625f989107c5b3e5686c09cec82d9a60caf47

I'll update the build script and rebuild the 13.1 and 13.2.

**Comment by partouf** [comment]
Aaaaaah, thank you

**Comment by dkm** [comment]
FTR, this has been introduced by [3acb929cc0beb79e6f4005eb22ee88b45e1cbc1d](https://gcc.gnu.org/cgit/gcc/commit/?id=3acb929cc0beb79e6f4005eb22ee88b45e1cbc1d).
First release to include the flag is gcc-12, and we have a special handling for gcc-12 in https://github.com/compiler-explorer/gcc-builder/blob/main/build/config/gcc12/enable_stacktrace

I'll add this option for all config >= 12 instead of having to add it to every future release.

**Comment by dkm** [comment]
Still need to rebuild and resquash.

**Comment by dkm** [comment]
building now:
- 13.1: https://github.com/compiler-explorer/infra/actions/runs/7877450092
- 13.2: https://github.com/compiler-explorer/infra/actions/runs/7877451846

**Comment by dkm** [comment]
Installed and squashed, but still not finding stacktrace. I've probably done something wrong.

**Comment by jwakely** [comment]
Backtrace support is enabled by default since GCC 14:
https://github.com/gcc-mirror/gcc/commit/fcede95472ceb4b63d0c131ed2f98bd79e0e360d

Would you like a PR to only do `CONFIG+=" --enable-libstdcxx-backtrace=yes"` for MAJOR == 12 and MAJOR == 13?

**Comment by mattgodbolt** [comment]
yes please (I think you did so already, right?)

**Comment by jwakely** [comment]
No, I made a similar change in https://github.com/compiler-explorer/gcc-builder/pull/31 for a different configure option.

I've submitted https://github.com/compiler-explorer/gcc-builder/pull/34 for the backtrace option now.
