### ISSUE TITLE
[BUG]: Ctrl + mouse wheel does not zoom in/out anymore

### ISSUE THREAD

**Issue by jengelh** [compiler-explorer/compiler-explorer#6186]
### Describe the bug

As of at least 2024-02-24, changing the text zoom level of the webpage of the godbolt.org instance via Ctrl-MWheelup/Ctrl-MWheelDn no longer works. Instead, it scrolls the text area (e.g. https://godbolt.org/z/94ezGvP47 )

### Steps to reproduce

1. Visit godbolt.org
2. Call up an existing paste, or type a lot of text
3. Focus the textarea
4. Ctrl-mousewheelup => nothing happens

5. Click somewhere outside the textarea
6. Ctrl-mousewheelup => Firefox does increase the fontsize

### Expected behavior

Not applicable

### Reproduction link

https://godbolt.org/z/94ezGvP47

### Screenshots

Not applicable

### Operating System

openSUSE Tumbleweed amd64 20240223

### Browser version

firefox 122.0.1

**Comment by dkm** [comment]
Possibly a monaco change.
As a workaround, move the mouse cursor outside of the text editor and you'll be able to zoom in/out.

**Comment by OfekShilon** [comment]
This changed in monaco 0.19 (!) released in 20.12.2019 (!!). Doesn't appear in the [release notes](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0190-20122019) so not entirely certain it's intentional.  You're welcome to take it up [with them](https://github.com/microsoft/monaco-editor/issues)  and if you do please link to it in this issue. 

Anyway, closing this one.
