### ISSUE TITLE
[BUG] you cannot really use compiler-explorer on mobile and ipad

### ISSUE THREAD

**Issue by Cr0a3** [compiler-explorer/compiler-explorer#7009]
### Describe the bug

Hi,
You cannot go into the input code field on mobile (idk if it is pixel 8 specific).
And you can't type in it on iPad.

Question: How often does the website sync its newest changed with the GitHub repo (when can I use ygen)?

Bye

### Steps to reproduce

Visit godbolt.org on mobile
Try to type something

### Expected behavior

You can type in it

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Pixel 8

### Browser version

Google newest

**Comment by AbrilRBS** [comment]
Hi @Cr0a3 thanks for your questions:

> You cannot go into the input code field on mobile (idk if it is pixel 8 specific).
And you can't type in it on iPad.

Yes, this is a known issue of the general site, mostly because our editor of choice, [Monaco Editor](https://github.com/microsoft/monaco-editor) has mobile support as a specific non-goal

Note that you can access https://godbolt.org/noscript to use a simple webpage if you need to compile something, which is the best we can provide for now :)

> How often does the website sync its newest changed with the GitHub repo (when can I use ygen)?

We usually make a release once in a while, usually around 1-2 weeks unless there's something urgent. I'm sure you won't have to wait much longer to see it live! (We usually also write in the PRs that the changes are now live)

**Comment by Cr0a3** [comment]
Thank you
