### ISSUE TITLE
Add tooltips/explanation of each language/pseudolanguage

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#703]
Some folks have been confused by (e.g.) what cppx is

**Comment by RabsRincon** [comment]
Note that selectize.js does not support tooltips on the items (At least not that I know of, please let me know if I'm wrong)

**Comment by mattgodbolt** [comment]
Agreed: I think we can probably do it with a richer description of each language (like the selectize input dropdown in the diff view).

**Comment by klosworks** [comment]
+1 to this. It is hard to find the relevant information. I was only able to find out cppx is by googling "cppx blue language compiler", and it took a few searches to find the right keywords. I found this: [https://github.com/lock3/cppx ](https://github.com/lock3/cppx ), I hope this is the thing. The page doesn't really explain anything though, so I would still like to find out what are these "blue" and "gold" languages and what is the difference. I can't find any explanation online.

**Comment by partouf** [comment]
@klosworks there's a brief explanation here -> https://github.com/compiler-explorer/compiler-explorer/issues/2201#issuecomment-705053870

**Comment by klosworks** [comment]
Based on the descriptions in the other issue thread, it seems that they are just intentionally obscure, so frankly I don't think they should be even available by default, although I understand that there may be practical reasons to keep them going. 

In the mean time why not change the names to something like "(unofficial) Cppx", "(unofficial) Cppx-blue" etc, so that the curious people don't waste time searching for something that doesn't even officially exist yet?

**Comment by RubenRBS** [comment]
Hi! I re-discovered this issue today, and with some changes we did to our UI some time ago, we can now add some popup info. I'll try to get this done this weekend
