### ISSUE TITLE
[COMPILER REQUEST]: GCC BPF is missing for 14.{1,2}

### ISSUE THREAD

**Issue by thesamesam** [compiler-explorer/compiler-explorer#7116]
### Compiler name

GCC

### Compiler version

14.1 BPF

### Compiler language

C

### Compiler homepage

https://gcc.gnu.org/gcc-14/changes.html

### Motivation

We have GCC 13.x for BPF and trunk, but not 14.x. Having 14 would be especially useful as it's the latest release of GCC and the one we're currently shipping for BPF in Gentoo.

**Comment by dkm** [comment]
That's odd, it should be there.
![bpf](https://github.com/user-attachments/assets/d7b07f02-f296-4833-ad22-4a710ec92326)

I guess you've looked at C++, not C. I did enable C++ in the past, because it worked and Jose told me that if it works, why not. But with latest release, it does not work at all, and only C is supported, so I've removed the C++ support.

**Comment by thesamesam** [comment]
Ugh, you're right, sorry. I was even aware of that problem and didn't notice. Could we just drop the BPF GCC compilers for C++ entirely?

**Comment by dkm** [comment]
I can hide them yes, sure. I thought it was nice to have them, but it's probably more confusing than useful.

**Comment by thesamesam** [comment]
I think it is, yeah, especially if we don't have consistent versions (entirely reasonably).

**Comment by dkm** [comment]
I'll hide the C++ compilers (hide and not kill, as we don't want to break existing shared links).
