### ISSUE TITLE
Crates for Rust

### ISSUE THREAD

**Issue by CryZe** [compiler-explorer/compiler-explorer#754]
Considering other languages have some libraries, this probably makes sense for Rust too, especially since Rust's std is fairly bare bones. Everyone uses a lot of crates even in fairly simple snippets, because of that. And that's totally fine, as it's absolutely easy with cargo to use external crates, so std doesn't even need to provide a lot of things. That however means that without any crates, you are fairly restricted, so both Godbolt and the original Rust playground are / were fairly suboptimal for Rust. The Rust Playground then added the Top 100 crates and now you can do a lot more with it. So I think it makes sense to do something similar for Godbolt. Maybe the implementation could even mostly be taken from the Playground source.

**Comment by luser** [comment]
The Rust Playground has a little Rust tool (naturally) to fetch the list of top crates it uses:
https://github.com/integer32llc/rust-playground/tree/master/top-crates

The biggest hurdle here would be that you'd either have to run `cargo` instead of just `rustc` to allow it to figure out the dependency tree ([the Rust Playground does this](https://github.com/integer32llc/rust-playground/blob/d8d0216a20d84756d1fa7a118f0e3a97ccb2de92/ui/src/sandbox.rs#L420)), or you'd have to pre-compile every available crate with every available version of `rustc` into known locations and manually pass the proper set of crates to `rustc`.

**Comment by partouf** [comment]
Main discussion here for some reason #754

**Comment by Dr-Emann** [comment]
That links back to this issue. I believe you meant to say the main discussion is at #1925

**Comment by NicholasSterling** [comment]
It would be nice to at least be able to use the rand crate, to generate random numbers.  The compiler pretty aggressively optimizes away code if it can statically determine what the result would be; it would be nice to be able to use rand to prevent that.  Or is there a better way?

**Comment by mattgodbolt** [comment]
The usual way we avoid compiler optimizing things away in other languages is to make it depend on a not-known-to-the-compiler value, like a function parameter (like the default `pub fn square` which depends on the `num` parameter).

**Comment by luser** [comment]
The Rust standard library includes an unstable [`std::hint::black_box`](https://doc.rust-lang.org/std/hint/fn.black_box.html) function that serves this purpose, FYI.

**Comment by mattgodbolt** [comment]
@luser that's great: thanks. In C++ I use inline-asm tricks to fake out things being used in some rare cases too, nice that rust has a builtin for this :)

**Comment by RubenRBS** [comment]
Hi! We're moving all the releated crate requests (And how to add support for it, which we still lack 3 years later) over to the linked issue :)
