### ISSUE TITLE
sh support

### ISSUE THREAD

**Issue by vbt1** [compiler-explorer/compiler-explorer#94]
really great project, could you add superh support on your demo site ? sh2 & sh4 would be a great addition :) thanks

**Comment by Kazade** [comment]
I know this is unlikely - but for us Dreamcast devs having SH4 + GCC 9 would be awesome :)

**Comment by dkm** [comment]
You want precisely GCC9? We can also provide more recent version if needed.
I'll see what we can easily provide later tonight (I see ct-ng has config for linux and baremetal, but I'll have to see if anything builds correctly before making any promise)

**Comment by mattgodbolt** [comment]
> I know this is unlikely - but for us Dreamcast devs having SH4 + GCC 9 would be awesome :)

I'd love this too, for nostalgia alone!

(I was engine developer for [Red Dog](https://en.wikipedia.org/wiki/Red_Dog:_Superior_Firepower) so a trip down memory lane wouuld be fun!)

**Comment by Kazade** [comment]
@dkm 4.8, and >= 9 would be good. The open source SDK was stuck on 4.8 for ages and quite a few projects still use it

@mattgodbolt Cool! Feel free to drop by the [Simulant Engine Discord](https://discord.com/invite/TRx94EV) if you want more nostalgia ;)

**Comment by dkm** [comment]
Ok, will see what I can do about these old version and keep you updated :)

**Comment by Kazade** [comment]
Thank you @dkm !

**Comment by dkm** [comment]
I've built 4.9.4, 9.5.0 and 12.2.0 for C/C++ for baremetal target. I'll see if I can enable more lang while I'm at it, but at least there will be some sh4 cross in the coming days :)

**Comment by mattgodbolt** [comment]
Amazing! Thanks!

**Comment by Kazade** [comment]
Brilliant! Thank you!

**Comment by dkm** [comment]
- 4.9.4 build : https://github.com/compiler-explorer/infra/actions/runs/3141640177
- 9.5.0 build: https://github.com/compiler-explorer/infra/actions/runs/3141646266
- 12.2.0 build: https://github.com/compiler-explorer/infra/actions/runs/3141647114

**Comment by dkm** [comment]
Hmmm, looks like the 4.9.4 is 'sh' and not 'sh4'. I'm not really sure what happens when building the toolchain with ct-ng having `unspecified` target. I'll rebuild with an explicit sh4 as it what I've been using for the 2 others and all configs are using 'sh4'.
By looking quickly at wikipedia I understand shX are different ISA, so not compatible and really different targets. Don't hesitate to correct me if I'm wrong :)

**Comment by vbt1** [comment]
don't miss sh2 big endian

**Comment by dkm** [comment]
What do you mean exactly ? You would like sh2 ? Or you won't be missing sh2?
I'm new to this sh* arch, so don't hesitate to be explicit about anything :D
My current tries at building a gcc 4.9.4 targeting sh4 is failing because newlib support is lacking. Probably something to tune, but not really sure.

**Comment by Kazade** [comment]
So the KallistiOS SDK has some custom patches for the toolchain - but I *believe* these are all things like adding its custom threading model etc. - you might find something useful in there though: https://github.com/KallistiOS/KallistiOS/tree/master/utils/dc-chain/patches

**Comment by Kazade** [comment]
Yeah makes sense! I think we use m4-single-only for DC :+1:

**Comment by dkm** [comment]
New name, new builds :)

- sh 4.9.4 https://github.com/compiler-explorer/infra/actions/runs/3145575089
- sh 9.5.0 https://github.com/compiler-explorer/infra/actions/runs/3145576107
- sh 12.2.0 https://github.com/compiler-explorer/infra/actions/runs/3145576957

**Comment by dkm** [comment]
@Kazade let is know if that works for your use cases :)

**Comment by vbt1** [comment]
i'll test too, i expected -m2 support (sh2) with just sh, it's not clear

**Comment by ijacquez** [comment]
> Ah, but then glibc isn't happy with sh2 as it's not supported :'). So I'll leave what was already in ct-ng, and some target won't be able to link to binaries because of missing libs, which I don't think is a real problem.
> 
> I still have to rename things from sh4 to sh.

Thank you for adding support. I just tested `sh` support and indeed it works. However, `-m2` does not (SH-2).

For SH-2 targets, Newlib is preferred. Otherwise, no standard library.

Is it still possible to add SH-2 back in? For reference, these are the `ct-ng` configs I have created to build a cross/canadian compiler targeting SH-2: https://github.com/ijacquez/libyaul-build-scripts.

**Comment by dkm** [comment]
That's probably me not really knowing this arch very well. I've observed that some targets work with linux/glibc and other with newlib. So `-m2` works for the 4.9.4 (newlib) but not with the others (glibc/linux).

So, maybe I should split the group from SH to `SH2` and `SH4`? Do you have better suggestion? I'm still a bit lost in these sh, sh2, sh3 and sh4 targets.

**Comment by ijacquez** [comment]
> That's probably me not really knowing this arch very well. I've observed that some targets work with linux/glibc and other with newlib. So `-m2` works for the 4.9.4 (newlib) but not with the others (glibc/linux).

The link has a config with GCC 11.2.0 (no newlib, but it should work). If there are any issues with anything above 4.9.4+newlib, let me know and I can try to help.

> So, maybe I should split the group from SH to `SH2` and `SH4`? Do you have better suggestion? I'm still a bit lost in these sh, sh2, sh3 and sh4 targets.

Yes. They're all part of the SH family, so the current `sh` entries should be marked as `sh4` and these SH-2 targets should just be `sh2`. Same with `sh3`.

**Comment by dkm** [comment]
That's what I had initially, but then realized that gcc was able to target several targets using different `-mXXX` options. The 4.9.4 can target sh2 and sh4 (but not sh3), but anything above can only target sh3 and sh4.
The best solution would be to have a config where gcc can target all versions. Is it possible?

**Comment by ijacquez** [comment]
> That's what I had initially, but then realized that gcc was able to target several targets using different `-mXXX` options. The 4.9.4 can target sh2 and sh4 (but not sh3), but anything above can only target sh3 and sh4.
> The best solution would be to have a config where gcc can target all versions. Is it possible?

I have never tried this myself, as I've only targeted SH-2. Maybe separate configs is the only way to go? Is that possible?

This is what I have set for SH-2:
```
CT_ARCH_SH=y
CT_ARCH="sh"
CT_ARCH_CHOICE_KSYM="SH"
CT_ARCH_SH_SHOW=y
CT_ARCH_SH_PKG_KSYM=""
CT_ARCH_SH_SH2=y
CT_ARCH_SH_VARIANT="sh2"
```

**Comment by dkm** [comment]
Hmmm, I'll have to dig this a bit more. I would like to avoid having too many compilers to builds when only 1 could do the job.

https://gcc.godbolt.org/z/W8os6YEEj

It's possible that gcc knows how to emit code for several targets but we can't link all combinations because it is missing some libs (e.g. newlib won't build for sh4, but glibc won't build for sh2). I think the link part is not that important in this case (correct me if I'm wrong).

I'll see if we can enable SH-2 in newer version without trying to build corresponding multilibs.

**Comment by ijacquez** [comment]
> It's possible that gcc knows how to emit code for several targets but we can't link all combinations because it is missing some libs (e.g. newlib won't build for sh4, but glibc won't build for sh2). I think the link part is not that important in this case (correct me if I'm wrong).

Do you have a log for the newlib SH-4 build errors?

Thank you for all the help @dkm.

**Comment by dkm** [comment]
No problem, thank you for your patience :) I'll pull the log and put the relevant part here :)

**Comment by dkm** [comment]
Ha, looks like that's something that I missed during the first investigation. Not targeting a particular SH version also works with newlib... but I didn't know that leaving "unspecified" was ok and was only trying with SH4, which was not working (probably because some tools do not like having `sh4-*` target and only want `sh-*`).

sooooo, we can't change existing compilers, but maybe I can had some more and hide the one already installed (9.5 and 12.2).

**Comment by ijacquez** [comment]
Glad to hear that there's a workaround!

**Comment by dkm** [comment]
Ok, so here's the plan:
 - we'll discretely swap the current 9.5 and 12.2 linux- by elf-
 - old sh links to these compilers will still work, but may yield different results (sorry about that... we usually don't do that, but decided sh-users during the last week were probably not that many...)
 - I'll drop fortran support as it's not available on elf- target... but I guess that's not a big loss, not sure there are many ppl doing fortran on sh targets anyway

**Comment by dkm** [comment]
9.5 build: https://github.com/compiler-explorer/infra/actions/runs/3235506227
12.2 build: https://github.com/compiler-explorer/infra/actions/runs/3235506940

**Comment by mattgodbolt** [comment]
I'll reinstall and re-squash once they're built! thanks @dkm

**Comment by mattgodbolt** [comment]
Looks like one of those died because the runner got killed (maybe it OOMed!? ugh)

**Comment by mattgodbolt** [comment]
I'm going to restart it and hope it magically fixes itself (hoho)

**Comment by dkm** [comment]
> I'll reinstall and re-squash once they're built! thanks @dkm

Great! As these are different compilers, we'll still need changes in infra and config before. I have everything ready but will test before. When compiler is built, I'll check my infra change and check that installed compilers work with my config changes :)

**Comment by mattgodbolt** [comment]
cool @dkm - I can delay installation until you're ready :)

**Comment by dkm** [comment]
https://github.com/compiler-explorer/infra/pull/850 <= infra changed, tested locally
https://github.com/compiler-explorer/compiler-explorer/pull/4154 <= config changes (also tested locally)

Then you can remove (as in `rm -rf`):
- /opt/compiler-explorer/sh/gcc-9.5.0/sh-multilib-linux-gnu/
- /opt/compiler-explorer/sh/gcc-12.2.0/sh-multilib-linux-gnu/

Thanks @mattgodbolt !

**Comment by mattgodbolt** [comment]
on it
